const RAW=window.OZORA_SCHEDULE||[];
const DATES=window.OZORA_DATES||[];
const VISIUM=RAW.filter(a=>a.stage==='Visium Garden');
const SCHEDULE=RAW.filter(a=>a.stage!=='Visium Garden').map(a=>{
  if(a.stage!=='Dragon Nest / Cooking Groove')return a;
  const hour=Number(a.start.split(':')[0]);
  return {...a,stage:hour>=10&&hour<17?'Cooking Groove':"Dragon's Nest"};
});
const LIVE_SCHEDULE=SCHEDULE.filter(a=>a.day>=2&&a.day<=8);
const STAGES=['Ozora Stage','The Dome','Cooking Groove',"Dragon's Nest",'Pumpui'];
const GENRES=[...new Set(SCHEDULE.map(a=>a.genre))].sort((a,b)=>a.localeCompare(b));
const COLORS={'Ozora Stage':'#ff4f62','The Dome':'#f2a33a','Cooking Groove':'#df8b32',"Dragon's Nest":'#36c96d','Pumpui':'#d100d7'};
const POSTERS=[['Ozora Stage','stage-ozora.jpg'],['Pumpui','stage-pumpui.jpg'],['The Dome','stage-dome.jpg'],["Dragon's Nest / Cooking Groove",'stage-dragon-cooking.jpg'],['Visium Garden / Ambyss','stage-visium.jpg']];
const IS_ACTS=new Set(['Avalon','Astrix','Ace Ventura','Altruism','Aardvarkk','Astral Projection','Atmos','Captain Hook','Freedom Fighters','GMS & Dickster','Modus','Skizologic','Spinal Fusion','Tristan','Psynonima']);
const FIRST={
  dont:['Astrix','Shpongle','Avalon','Hilight Tribe'],
  core:['Ace Ventura','Merkaba','Asgard','Kalya Scintilla'],
  reset:['Solar Fields','Zen Baboon','Nick Interchill','Globular']
};
const KOFI_URL='https://ko-fi.com/';
const APP_URL='https://mudita1973.github.io/Ozora2026_2.0/';

const I18N={
de:{home:'Start',all:'Alle',live:'Live',myPlan:'Mein Plan',journal:'Notizen',routing:'Routing',first:'First Timer',search:'Acts durchsuchen …',allDays:'Alle Tage',allActs:'Alle Acts',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Festival-Ablauf',arrival:'Anreise',arrivalSub:'Fr 24.7.',preDays:'Pumpui Pre-Days',preDaysSub:'Sa 25.7. + So 26.7.',openStages:'Alle Stages öffnen',openStagesSub:'Mo 27.7.',closing:'Festivalende',closingSub:'Di 4.8.',acts:'Acts',stages:'Stages',saved:'gespeichert',ratings:'Ratings',schedule:'Zeitplan',filters:'Filter',duration:'Dauer',minutes:'Min.',personalRange:'Persönlicher Bereich',commentPlaceholder:'Your personal comment (English)',share:'Plan teilen',clearAll:'Alle löschen',emptyPlan:'Noch keine Acts gespeichert.',emptyRating:'Bewerte Acts ab 7, um dein Routing zu erzeugen.',liveNow:'Jetzt live',nextActs:'Als Nächstes',nothingLive:'Aktuell läuft auf diesen fünf Stages nichts.',conflicts:'Wichtige Überschneidungen',alternative:'Alternative',recommendation:'Empfehlung',firstIntro:'Orientierung für den ersten Ozora-Besuch.',missingAmbyss:'Die gelieferten Ambyss/Visium-Daten beginnen erst am 28.7. Für Ambyss/Y2KZERO am 25.–26.7. fehlen noch die Poster oder die Act-Liste.',credit:'First-Timer-Konzept und Community-Credit: Astro S / PsySmurfs.',dontMiss:"DON'T MISS",core:'CORE',reset:'RESET',posters:'Originalposter',clearCache:'Cache wurde geleert.',copied:'Plan wurde kopiert.',removed:'Aus dem Plan entfernt.',added:'Zum Plan hinzugefügt.',confirmClear:'Wirklich den gesamten Plan löschen?',chooseLanguage:'Wähle deine Sprache',continue:'Weiter',disclaimer:'Inoffizielle Fan-App. Nicht mit O.Z.O.R.A. Festival verbunden. Zeitplan vor Ort prüfen.',helpTitle:'Anleitung',close:'Schließen',intro:'Überblick',install:'Installation',navigation:'Navigation',planHelp:'Mein Plan',ratingHelp:'Ratings',liveHelp:'Live-Anzeige',routingHelp:'Routing',offline:'Offline',privacy:'Datenschutz',helpTexts:['Die App bündelt fünf Hauptstages und die Pumpui Pre-Days.','In Safari/Chrome über „Zum Home-Bildschirm“ installieren.','Tabs, Tagesfilter, Suche und Ratingfilter kombinieren.','Stern antippen, teilen oder vollständig leeren.','Min/Max von 0–10 setzen; 9+ wird hervorgehoben.','Live- und Next-Badges aktualisieren sich jede Minute.','Acts ab 7 werden gruppiert; Überschneidungen erscheinen als Alternativen.','Poster, Plan, Ratings und UI funktionieren nach dem ersten Laden offline.','Kein Login, keine Tracker; Daten bleiben lokal im Browser.']},
en:{home:'Home',all:'All',live:'Live',myPlan:'My Plan',journal:'Notes',routing:'Routing',first:'First Timer',search:'Search all acts …',allDays:'All days',allActs:'All acts',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Festival timeline',arrival:'Arrival day',arrivalSub:'Fri 24 Jul',preDays:'Pumpui Pre-Days',preDaysSub:'Sat 25 + Sun 26 Jul',openStages:'All stages open',openStagesSub:'Mon 27 Jul',closing:'Festival ends',closingSub:'Tue 4 Aug',acts:'Acts',stages:'Stages',saved:'saved',ratings:'Ratings',schedule:'Schedule',filters:'Filters',duration:'Duration',minutes:'min',personalRange:'Personal range',commentPlaceholder:'Your personal comment (English)',share:'Share plan',clearAll:'Clear all',emptyPlan:'No acts saved yet.',emptyRating:'Rate acts 7 or higher to build your routing.',liveNow:'Live now',nextActs:'Up next',nothingLive:'Nothing is currently playing on these five stages.',conflicts:'Key overlaps',alternative:'Alternative',recommendation:'Recommendation',firstIntro:'Orientation for your first Ozora visit.',missingAmbyss:'The supplied Ambyss/Visium data starts on 28 Jul. The Ambyss/Y2KZERO poster or act list for 25–26 Jul is still missing.',credit:'First-timer concept and community credit: Astro S / PsySmurfs.',dontMiss:"DON'T MISS",core:'CORE',reset:'RESET',posters:'Original posters',clearCache:'Cache cleared.',copied:'Plan copied.',removed:'Removed from plan.',added:'Added to plan.',confirmClear:'Clear the entire plan?',chooseLanguage:'Choose your language',continue:'Continue',disclaimer:'Unofficial fan app. Not affiliated with O.Z.O.R.A. Festival. Verify times on site.',helpTitle:'Guide',close:'Close',intro:'Overview',install:'Installation',navigation:'Navigation',planHelp:'My Plan',ratingHelp:'Ratings',liveHelp:'Live display',routingHelp:'Routing',offline:'Offline',privacy:'Privacy',helpTexts:['The app combines five main stages and the Pumpui Pre-Days.','Install from Safari/Chrome using “Add to Home Screen”.','Combine tabs, day filters, search and rating filters.','Tap the star, share the plan or clear it completely.','Set a 0–10 min/max range; 9+ is highlighted.','Live and next badges update every minute.','Acts rated 7+ are grouped; overlaps appear as alternatives.','Posters, plan, ratings and UI work offline after the first load.','No login or trackers; data stays in your browser.']},
es:{home:'Inicio',all:'Todos',live:'En vivo',myPlan:'Mi plan',journal:'Notas',routing:'Rutas',first:'Primera vez',search:'Buscar actuaciones …',allDays:'Todos los días',allActs:'Todas',rating7:'7+',rating8:'8+',rating9:'9+ ÉPICO',festival:'Cronología del festival',arrival:'Llegada',arrivalSub:'Vie 24/7',preDays:'Pre-Days de Pumpui',preDaysSub:'Sáb 25 + Dom 26/7',openStages:'Abren todos los escenarios',openStagesSub:'Lun 27/7',closing:'Fin del festival',closingSub:'Mar 4/8',acts:'Actuaciones',stages:'Escenarios',saved:'guardadas',ratings:'Valoraciones',schedule:'Horario',filters:'Filtros',duration:'Duración',minutes:'min',personalRange:'Rango personal',commentPlaceholder:'Your personal comment (English)',share:'Compartir plan',clearAll:'Borrar todo',emptyPlan:'Aún no hay actuaciones guardadas.',emptyRating:'Valora actuaciones con 7 o más para crear tu ruta.',liveNow:'Ahora en vivo',nextActs:'A continuación',nothingLive:'Ahora mismo no hay actuaciones en estos cinco escenarios.',conflicts:'Cruces importantes',alternative:'Alternativa',recommendation:'Recomendación',firstIntro:'Orientación para tu primera visita a Ozora.',missingAmbyss:'Los datos de Ambyss/Visium proporcionados empiezan el 28/7. Falta el póster o la lista de Ambyss/Y2KZERO del 25–26/7.',credit:'Concepto First Timer y crédito de comunidad: Astro S / PsySmurfs.',dontMiss:'IMPERDIBLE',core:'ESENCIAL',reset:'DESCANSO',posters:'Pósteres originales',clearCache:'Caché borrada.',copied:'Plan copiado.',removed:'Eliminado del plan.',added:'Añadido al plan.',confirmClear:'¿Borrar todo el plan?',chooseLanguage:'Elige tu idioma',continue:'Continuar',disclaimer:'Aplicación no oficial. Sin afiliación con O.Z.O.R.A. Festival. Comprueba los horarios allí.',helpTitle:'Guía',close:'Cerrar',intro:'Resumen',install:'Instalación',navigation:'Navegación',planHelp:'Mi plan',ratingHelp:'Valoraciones',liveHelp:'En vivo',routingHelp:'Rutas',offline:'Sin conexión',privacy:'Privacidad',helpTexts:['La app reúne cinco escenarios principales y los Pre-Days de Pumpui.','Instálala desde Safari/Chrome con “Añadir a pantalla de inicio”.','Combina pestañas, días, búsqueda y filtros de valoración.','Pulsa la estrella, comparte o borra el plan.','Define un rango mínimo/máximo de 0–10; 9+ se resalta.','Los indicadores Live y Next se actualizan cada minuto.','Las actuaciones con 7+ se agrupan; los cruces aparecen como alternativas.','Pósteres, plan, valoraciones e interfaz funcionan offline tras la primera carga.','Sin cuenta ni rastreadores; los datos quedan en el navegador.']},
hu:{home:'Kezdőlap',all:'Mind',live:'Élő',myPlan:'Tervem',journal:'Jegyzetek',routing:'Útvonal',first:'Első alkalom',search:'Fellépők keresése …',allDays:'Minden nap',allActs:'Minden fellépő',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Fesztivál-idővonal',arrival:'Érkezés',arrivalSub:'Júl. 24., péntek',preDays:'Pumpui előnapok',preDaysSub:'Júl. 25–26.',openStages:'Minden színpad nyit',openStagesSub:'Júl. 27., hétfő',closing:'Fesztivál vége',closingSub:'Aug. 4., kedd',acts:'Fellépések',stages:'Színpadok',saved:'mentve',ratings:'Értékelések',schedule:'Program',filters:'Szűrők',duration:'Időtartam',minutes:'perc',personalRange:'Személyes tartomány',commentPlaceholder:'Your personal comment (English)',share:'Terv megosztása',clearAll:'Összes törlése',emptyPlan:'Még nincs mentett fellépő.',emptyRating:'Értékeld 7 fölé a fellépőket az útvonalhoz.',liveNow:'Most élőben',nextActs:'Következik',nothingLive:'Jelenleg egyik színpadon sincs műsor.',conflicts:'Fontos átfedések',alternative:'Alternatíva',recommendation:'Ajánlás',firstIntro:'Segítség az első Ozora-látogatáshoz.',missingAmbyss:'A kapott Ambyss/Visium adatok július 28-án kezdődnek. A július 25–26-i Ambyss/Y2KZERO plakát vagy fellépőlista még hiányzik.',credit:'First Timer koncepció és közösségi kredit: Astro S / PsySmurfs.',dontMiss:'KI NE HAGYD',core:'ALAP',reset:'PIHENŐ',posters:'Eredeti plakátok',clearCache:'Gyorsítótár törölve.',copied:'Terv másolva.',removed:'Eltávolítva a tervből.',added:'Hozzáadva a tervhez.',confirmClear:'Törlöd a teljes tervet?',chooseLanguage:'Válassz nyelvet',continue:'Tovább',disclaimer:'Nem hivatalos rajongói app. Nem áll kapcsolatban az O.Z.O.R.A. Fesztivállal. A helyszínen ellenőrizd az időpontokat.',helpTitle:'Útmutató',close:'Bezárás',intro:'Áttekintés',install:'Telepítés',navigation:'Navigáció',planHelp:'Tervem',ratingHelp:'Értékelések',liveHelp:'Élő kijelzés',routingHelp:'Útvonal',offline:'Offline',privacy:'Adatvédelem',helpTexts:['Az app öt fő színpadot és a Pumpui előnapokat fogja össze.','Safari/Chrome: „Hozzáadás a Főképernyőhöz”.','Kombináld a füleket, napokat, keresést és értékelésszűrőt.','Csillaggal ments, oszd meg vagy töröld a tervet.','Állíts be 0–10 minimum/maximum tartományt; a 9+ kiemelt.','A Live és Next jelvény percenként frissül.','A 7+ fellépők csoportosítva jelennek meg, az átfedések alternatívák.','A plakátok, terv, értékelések és felület az első betöltés után offline működik.','Nincs bejelentkezés vagy követés; az adatok a böngészőben maradnak.']}
};
const EXTRA_I18N={
  de:{discover:'Entdecken',recommendations:'Empfehlungen',allGenres:'Alle Genres',newMix:'Neuer Mix',discoverIntro:'Finde Acts außerhalb deines Plans und entdecke neue Stages und Sounds.',recommendIntro:'Basiert auf deinem Plan, deinen Ratings, Genres und bevorzugten Stages.',forYou:'Für dich',curated:'Festival-Highlights',noPreferences:'Speichere oder bewerte Acts ab 7, damit die Empfehlungen persönlicher werden.',match:'Treffer',reminders:'Erinnerungen',enableReminders:'Erinnerungen aktivieren',disableReminders:'Erinnerungen deaktivieren',reminderOn:'Erinnerungen sind aktiv',reminderOff:'Erinnerungen sind aus',reminderBefore:'Minuten vor Beginn',reminderSaved:'Erinnerungseinstellungen gespeichert.',notificationBlocked:'Benachrichtigungen wurden im Browser blockiert.',notificationUnsupported:'Dieser Browser unterstützt keine lokalen Benachrichtigungen.',reminderLimit:'Erinnerungen werden lokal geprüft, solange die App geöffnet oder im Hintergrund aktiv ist. Bei vollständig geschlossener App sind sie ohne Push-Server nicht garantiert.',startsSoon:'beginnt bald',basedOnGenre:'Passendes Genre',basedOnStage:'Bevorzugte Stage',surprise:'Überraschungsmix',shareApp:'▦ App per QR teilen',shareTitle:'App teilen',scanToShare:'Öffne den QR-Code, damit andere die App direkt mit ihrem Handy aufrufen können.',showQr:'QR-Code anzeigen',copyLink:'Link kopieren',shareLink:'Link teilen',linkCopied:'App-Link wurde kopiert.',supportApp:'☕ App unterstützen (Ko-fi)',donationNote:'Ko-fi ist eine freiwillige Spendenmöglichkeit für alle, denen die App gefällt.',shareText:'Ozora 2026 Festival Planner öffnen'},
  en:{discover:'Discover',recommendations:'Recommendations',allGenres:'All genres',newMix:'New mix',discoverIntro:'Find acts outside your plan and discover new stages and sounds.',recommendIntro:'Based on your plan, ratings, genres and preferred stages.',forYou:'For you',curated:'Festival highlights',noPreferences:'Save or rate acts 7+ to make recommendations more personal.',match:'match',reminders:'Reminders',enableReminders:'Enable reminders',disableReminders:'Disable reminders',reminderOn:'Reminders are on',reminderOff:'Reminders are off',reminderBefore:'Minutes before start',reminderSaved:'Reminder settings saved.',notificationBlocked:'Notifications were blocked by the browser.',notificationUnsupported:'This browser does not support local notifications.',reminderLimit:'Reminders are checked locally while the app is open or active in the background. They are not guaranteed when the app is fully closed without a push server.',startsSoon:'starts soon',basedOnGenre:'Matching genre',basedOnStage:'Preferred stage',surprise:'Surprise mix',shareApp:'▦ Share app by QR',shareTitle:'Share the app',scanToShare:'Open the QR code so others can access the app directly with their phone.',showQr:'Show QR code',copyLink:'Copy link',shareLink:'Share link',linkCopied:'App link copied.',supportApp:'☕ Support the app (Ko-fi)',donationNote:'Ko-fi is an optional donation for anyone who enjoys the app.',shareText:'Open the Ozora 2026 Festival Planner'},
  es:{discover:'Descubrir',recommendations:'Recomendaciones',allGenres:'Todos los géneros',newMix:'Nueva mezcla',discoverIntro:'Encuentra actuaciones fuera de tu plan y descubre nuevos escenarios y sonidos.',recommendIntro:'Basado en tu plan, valoraciones, géneros y escenarios preferidos.',forYou:'Para ti',curated:'Destacados del festival',noPreferences:'Guarda o valora actuaciones con 7+ para personalizar las recomendaciones.',match:'coincidencia',reminders:'Recordatorios',enableReminders:'Activar recordatorios',disableReminders:'Desactivar recordatorios',reminderOn:'Recordatorios activos',reminderOff:'Recordatorios desactivados',reminderBefore:'Minutos antes del inicio',reminderSaved:'Configuración de recordatorios guardada.',notificationBlocked:'El navegador ha bloqueado las notificaciones.',notificationUnsupported:'Este navegador no admite notificaciones locales.',reminderLimit:'Los recordatorios se comprueban localmente mientras la app está abierta o activa en segundo plano. Sin un servidor push no se garantizan con la app totalmente cerrada.',startsSoon:'empieza pronto',basedOnGenre:'Género compatible',basedOnStage:'Escenario preferido',surprise:'Mezcla sorpresa',shareApp:'▦ Compartir app por QR',shareTitle:'Compartir la app',scanToShare:'Abre el código QR para que otras personas accedan directamente desde su móvil.',showQr:'Mostrar código QR',copyLink:'Copiar enlace',shareLink:'Compartir enlace',linkCopied:'Enlace de la app copiado.',supportApp:'☕ Apoyar la app (Ko-fi)',donationNote:'Ko-fi es una donación voluntaria para quienes disfrutan de la app.',shareText:'Abrir Ozora 2026 Festival Planner'},
  hu:{discover:'Felfedezés',recommendations:'Ajánlások',allGenres:'Minden műfaj',newMix:'Új válogatás',discoverIntro:'Találj új fellépőket a terveden kívül, és fedezz fel új színpadokat és hangzásokat.',recommendIntro:'A terved, értékeléseid, műfajaid és kedvelt színpadaid alapján.',forYou:'Neked',curated:'Fesztivál-kiemelések',noPreferences:'Ments vagy értékelj legalább 7 pontra fellépőket a személyesebb ajánlásokhoz.',match:'egyezés',reminders:'Emlékeztetők',enableReminders:'Emlékeztetők bekapcsolása',disableReminders:'Emlékeztetők kikapcsolása',reminderOn:'Az emlékeztetők aktívak',reminderOff:'Az emlékeztetők ki vannak kapcsolva',reminderBefore:'Perccel a kezdés előtt',reminderSaved:'Emlékeztető-beállítások mentve.',notificationBlocked:'A böngésző letiltotta az értesítéseket.',notificationUnsupported:'Ez a böngésző nem támogatja a helyi értesítéseket.',reminderLimit:'Az emlékeztetők helyben futnak, amíg az app nyitva van vagy aktív a háttérben. Teljesen bezárt appnál push szerver nélkül nem garantáltak.',startsSoon:'hamarosan kezdődik',basedOnGenre:'Illő műfaj',basedOnStage:'Kedvelt színpad',surprise:'Meglepetés válogatás',shareApp:'▦ App megosztása QR-kóddal',shareTitle:'App megosztása',scanToShare:'Nyisd meg a QR-kódot, hogy mások közvetlenül elérjék az appot a telefonjukon.',showQr:'QR-kód megjelenítése',copyLink:'Link másolása',shareLink:'Link megosztása',linkCopied:'Az app linkje kimásolva.',supportApp:'☕ Az app támogatása (Ko-fi)',donationNote:'A Ko-fi önkéntes adományozási lehetőség azoknak, akiknek tetszik az app.',shareText:'Az Ozora 2026 Festival Planner megnyitása'}
};
for(const language of Object.keys(EXTRA_I18N))Object.assign(I18N[language],EXTRA_I18N[language]);
I18N.de.helpTexts[2]='Nutze Tabs, Tages-, Genre- und Ratingfilter, Suche, Entdecken und persönliche Empfehlungen. Über „App per QR teilen“ können andere den Planner direkt öffnen.';
I18N.de.helpTexts[5]='Live- und Next-Badges aktualisieren sich jede Minute. Die Glocke erinnert dich lokal vor gespeicherten Acts.';
I18N.en.helpTexts[2]='Use tabs, day, genre and rating filters, search, Discover and personal recommendations. “Share app by QR” lets others open the planner directly.';
I18N.en.helpTexts[5]='Live and next badges update every minute. The bell can remind you locally before saved acts.';
I18N.es.helpTexts[2]='Usa pestañas, filtros de día, género y valoración, búsqueda, Descubrir y recomendaciones personales. Con “Compartir app por QR” otras personas pueden abrir el planner directamente.';
I18N.es.helpTexts[5]='Los indicadores Live y Next se actualizan cada minuto. La campana puede avisarte localmente antes de actuaciones guardadas.';
I18N.hu.helpTexts[2]='Használd a füleket, a nap-, műfaj- és értékelésszűrőket, a keresést, a Felfedezést és a személyes ajánlásokat. Az „App megosztása QR-kóddal” gombbal mások közvetlenül megnyithatják a plannert.';
I18N.hu.helpTexts[5]='A Live és Next jelvény percenként frissül. A csengő helyben emlékeztethet a mentett fellépések előtt.';
I18N.de.helpTexts[8]='Kein Login, keine Tracker; Daten bleiben lokal im Browser. Ko-fi ist ausschließlich eine freiwillige Spendenmöglichkeit.';
I18N.en.helpTexts[8]='No login or trackers; data stays in your browser. Ko-fi is only an optional donation method.';
I18N.es.helpTexts[8]='Sin cuenta ni rastreadores; los datos quedan en el navegador. Ko-fi es únicamente una donación voluntaria.';
I18N.hu.helpTexts[8]='Nincs bejelentkezés vagy követés; az adatok a böngészőben maradnak. A Ko-fi kizárólag önkéntes adományozási lehetőség.';
const IMPORT_I18N={
  de:{indianSpirit:'Indian Spirit',isIntro:'Alle Ozora-Acts, die auch beim Indian Spirit 2026 spielen.',isSource:'Geprüfter Festivalvergleich · 15 übereinstimmende Künstler.',excelImport:'Excel-Import',importIntro:'Importiere Ratings, Kommentare, Links und Plan-Auswahl lokal aus einer Excel-Datei.',chooseExcel:'Excel-Datei auswählen',downloadTemplate:'Importvorlage herunterladen',importPrivacy:'Die Datei bleibt auf deinem Gerät und wird nicht hochgeladen.',importSupports:'Unterstützt die Ozora-Importvorlage und kompatible Tabellenformate.',importReady:'Import bereit',recognizedRows:'Excel-Zeilen erkannt',matchedActs:'Acts mit importierbaren Daten',unmatchedArtists:'nicht zugeordnet',applyImport:'Import übernehmen',importDone:'Excel-Daten wurden übernommen.',importError:'Die Excel-Datei konnte nicht gelesen werden.',noImportData:'Keine passenden Ozora-Acts mit importierbaren Daten gefunden.',noPersonalData:'Der Zeitplan wurde erkannt, aber die Datei enthält keine ausgefüllten Ratings, Kommentare, Links oder Plan-Markierungen.',templateHint:'Empfohlen: Nutze die vorbefüllte Vorlage mit stabiler Act-ID und einer Zeile pro Act.',personalData:'Persönliche Daten'},
  en:{indianSpirit:'Indian Spirit',isIntro:'All Ozora acts that also play Indian Spirit 2026.',isSource:'Verified festival comparison · 15 matching artists.',excelImport:'Excel import',importIntro:'Import ratings, comments, links and plan selections locally from an Excel file.',chooseExcel:'Choose Excel file',downloadTemplate:'Download import template',importPrivacy:'The file stays on your device and is not uploaded.',importSupports:'Supports the Ozora import template and compatible spreadsheet formats.',importReady:'Import ready',recognizedRows:'Excel rows recognized',matchedActs:'acts with importable data',unmatchedArtists:'not matched',applyImport:'Apply import',importDone:'Excel data imported.',importError:'The Excel file could not be read.',noImportData:'No matching Ozora acts with importable data were found.',noPersonalData:'The schedule was recognized, but the file contains no completed ratings, comments, links or plan selections.',templateHint:'Recommended: use the pre-filled template with a stable act ID and one row per act.',personalData:'Personal data'},
  es:{indianSpirit:'Indian Spirit',isIntro:'Todas las actuaciones de Ozora que también participan en Indian Spirit 2026.',isSource:'Comparación de festivales verificada · 15 artistas coincidentes.',excelImport:'Importar Excel',importIntro:'Importa localmente valoraciones, comentarios, enlaces y selecciones del plan desde un archivo Excel.',chooseExcel:'Elegir archivo Excel',downloadTemplate:'Descargar plantilla',importPrivacy:'El archivo permanece en tu dispositivo y no se sube.',importSupports:'Admite la plantilla de Ozora y formatos de hoja de cálculo compatibles.',importReady:'Importación preparada',recognizedRows:'filas de Excel reconocidas',matchedActs:'actuaciones con datos importables',unmatchedArtists:'sin asignar',applyImport:'Aplicar importación',importDone:'Datos de Excel importados.',importError:'No se pudo leer el archivo Excel.',noImportData:'No se encontraron actuaciones de Ozora con datos importables.',noPersonalData:'Se reconoció el horario, pero el archivo no contiene valoraciones, comentarios, enlaces ni selecciones del plan completados.',templateHint:'Recomendado: usa la plantilla precargada con ID estable y una fila por actuación.',personalData:'Datos personales'},
  hu:{indianSpirit:'Indian Spirit',isIntro:'Minden Ozora-fellépő, aki az Indian Spirit 2026-on is játszik.',isSource:'Ellenőrzött fesztivál-összehasonlítás · 15 egyező előadó.',excelImport:'Excel-import',importIntro:'Értékelések, megjegyzések, linkek és tervkijelölések helyi importálása Excel-fájlból.',chooseExcel:'Excel-fájl kiválasztása',downloadTemplate:'Importsablon letöltése',importPrivacy:'A fájl az eszközödön marad, nem kerül feltöltésre.',importSupports:'Támogatja az Ozora importsablont és a kompatibilis táblázatkezelő-formátumokat.',importReady:'Importálásra kész',recognizedRows:'felismert Excel-sor',matchedActs:'importálható adattal rendelkező fellépés',unmatchedArtists:'nem párosított',applyImport:'Import alkalmazása',importDone:'Az Excel-adatok importálva.',importError:'Az Excel-fájl nem olvasható.',noImportData:'Nem található importálható adattal rendelkező Ozora-fellépő.',noPersonalData:'A programot felismerte az alkalmazás, de a fájl nem tartalmaz kitöltött értékelést, megjegyzést, hivatkozást vagy tervkijelölést.',templateHint:'Ajánlott: használd az előre kitöltött sablont stabil fellépésazonosítóval és fellépésenként egy sorral.',personalData:'Személyes adatok'}
};
for(const language of Object.keys(IMPORT_I18N))Object.assign(I18N[language],IMPORT_I18N[language]);
I18N.de.helpTexts[0]='Die App bündelt fünf Hauptstages, Pumpui Pre-Days, Indian-Spirit-Überschneidungen und einen lokalen Excel-Import.';
I18N.en.helpTexts[0]='The app combines five main stages, Pumpui Pre-Days, Indian Spirit overlaps and a local Excel import.';
I18N.es.helpTexts[0]='La app reúne cinco escenarios principales, los Pre-Days de Pumpui, coincidencias con Indian Spirit y una importación local de Excel.';
I18N.hu.helpTexts[0]='Az app öt fő színpadot, a Pumpui előnapokat, Indian Spirit-egyezéseket és helyi Excel-importot fog össze.';
Object.assign(I18N.de,{rateAct:'Bewerten',rateHint:'Tippe eine Zahl für eine schnelle Bewertung oder nutze den Bereich darunter.',ratingSaved:'Bewertung gespeichert.'});
Object.assign(I18N.en,{rateAct:'Rate act',rateHint:'Tap a number for a quick rating or use the range below.',ratingSaved:'Rating saved.'});
Object.assign(I18N.es,{rateAct:'Valorar',rateHint:'Toca un número para valorar rápido o usa el rango inferior.',ratingSaved:'Valoración guardada.'});
Object.assign(I18N.hu,{rateAct:'Értékelés',rateHint:'Gyors értékeléshez koppints egy számra, vagy használd az alsó tartományt.',ratingSaved:'Értékelés mentve.'});
const UI_LABELS={
  de:{language:'Sprache',compact:'Kompaktmodus',guide:'Anleitung',cache:'Cache leeren',reminders:'Erinnerungen',areas:'Bereiche',mainNav:'Hauptnavigation',close:'Schließen',artist:'Künstlerprofil',comment:'Kommentar und Rating',opening:'Eröffnungszeremonie'},
  en:{language:'Language',compact:'Compact mode',guide:'Guide',cache:'Clear cache',reminders:'Reminders',areas:'Sections',mainNav:'Main navigation',close:'Close',artist:'Artist profile',comment:'Comment and rating',opening:'Opening Ceremony'},
  es:{language:'Idioma',compact:'Modo compacto',guide:'Guía',cache:'Borrar caché',reminders:'Recordatorios',areas:'Secciones',mainNav:'Navegación principal',close:'Cerrar',artist:'Perfil del artista',comment:'Comentario y valoración',opening:'Ceremonia de apertura'},
  hu:{language:'Nyelv',compact:'Kompakt mód',guide:'Útmutató',cache:'Gyorsítótár törlése',reminders:'Emlékeztetők',areas:'Területek',mainNav:'Fő navigáció',close:'Bezárás',artist:'Előadói profil',comment:'Megjegyzés és értékelés',opening:'Megnyitó ünnepség'}
};

const safeJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}};
let state={route:location.hash.slice(1)||'home',lang:localStorage.ozLang||'de',day:'all',stage:'all',genre:'all',rating:0,search:'',plan:safeJSON('ozPlanV4',[]),reviews:safeJSON('ozReviewsV4',{}),compact:localStorage.ozCompact==='1',discoverySeed:1,reminders:localStorage.ozRemindersV42==='1',reminderMinutes:Number(localStorage.ozReminderMinutesV42||15),notified:safeJSON('ozNotifiedV42',{})};
state.importPreview=null;
const $=s=>document.querySelector(s),t=k=>I18N[state.lang][k]??k;
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dateLabel=i=>new Intl.DateTimeFormat(state.lang,{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(`${DATES[i]}T12:00:00`));
const mins=x=>{const[h,m]=x.split(':').map(Number);return h*60+m};
const duration=a=>{let d=mins(a.end)-mins(a.start);if(d<=0)d+=1440;return d};
const startDate=a=>new Date(`${DATES[a.day]}T${a.start}:00`);
const endDate=a=>{const e=new Date(`${DATES[a.day]}T${a.end}:00`);if(e<=startDate(a))e.setDate(e.getDate()+1);return e};
const review=id=>state.reviews[id]||{min:0,max:0,comment:''};
const score=id=>{const r=review(id);return (Number(r.min)+Number(r.max))/2};
const links=name=>{const importedAct=SCHEDULE.find(act=>act.artist===name&&(state.reviews[act.id]?.youtube||state.reviews[act.id]?.spotify)),imported=importedAct?state.reviews[importedAct.id]:{};return {YouTube:imported.youtube||`https://www.youtube.com/results?search_query=${encodeURIComponent(name+' live')}`,Spotify:imported.spotify||`https://open.spotify.com/search/${encodeURIComponent(name)}`}};
const persist=()=>{localStorage.ozPlanV4=JSON.stringify(state.plan);localStorage.ozReviewsV4=JSON.stringify(state.reviews);localStorage.ozLang=state.lang;localStorage.ozCompact=state.compact?'1':'0';localStorage.ozRemindersV42=state.reminders?'1':'0';localStorage.ozReminderMinutesV42=String(state.reminderMinutes);localStorage.ozNotifiedV42=JSON.stringify(state.notified)};

function statusFor(a,now=new Date()){
  if(now>=startDate(a)&&now<endDate(a))return 'live';
  const next=SCHEDULE.filter(x=>x.stage===a.stage&&startDate(x)>now).sort((x,y)=>startDate(x)-startDate(y))[0];
  return next?.id===a.id?'next':'';
}
function stageColor(stage){return COLORS[stage]||'#888'}
function ratingText(id){const r=state.reviews[id];return r?`${Number(r.min).toFixed(1)}–${Number(r.max).toFixed(1)}`:'–'}
function card(a,open=false){const r=review(a.id),status=statusFor(a),epic=score(a.id)>=9,saved=state.plan.includes(a.id),l=links(a.artist),ui=UI_LABELS[state.lang],artist=esc(a.artist);return `<article class="act-card ${epic?'epic':''} ${open?'open':''}" style="--stage:${stageColor(a.stage)}" data-card="${esc(a.id)}"><div class="act-main"><div class="time">${a.start}<small>${a.end} · ${duration(a)} ${t('minutes')}</small></div><div><button class="artist-button" data-artist="${artist}" aria-label="${ui.artist}: ${artist}">${artist}</button><div><span class="stage-badge">${esc(a.stage)}</span>${IS_ACTS.has(a.artist)?'<span class="tag is">🪶 IS</span>':''}${saved&&state.reminders?'<span class="tag reminder-tag">🔔</span>':''}${status?`<span class="status-badge ${status}">${status==='live'?'● LIVE':'NEXT'}</span>`:''}<button class="rating-badge rating-open" data-rate="${esc(a.id)}" aria-label="${t('rateAct')}">${ratingText(a.id)}</button></div><div class="meta">${esc(a.genre)} · ${esc(a.type)}</div></div><div class="row-actions"><a href="${l.YouTube}" target="_blank" rel="noopener" aria-label="YouTube">▶</a><a href="${l.Spotify}" target="_blank" rel="noopener" aria-label="Spotify">♫</a><button class="rate-action" data-rate="${esc(a.id)}" aria-label="${t('rateAct')}">0–10</button><button data-save="${esc(a.id)}" class="${saved?'saved':''}" aria-label="${t('myPlan')}">${saved?'★':'☆'}</button></div></div><div class="details"><div class="rate-heading"><b>${t('rateAct')}</b><small>${t('rateHint')}</small></div><div class="quick-ratings" role="group" aria-label="${t('rateAct')}">${[5,6,7,8,9,10].map(value=>`<button data-quick-rating="${esc(a.id)}" data-value="${value}" class="${Number(r.min)===value&&Number(r.max)===value?'selected':''}">${value}</button>`).join('')}</div><div class="rating-sliders"><label>${t('personalRange')} min: <b data-min-label="${esc(a.id)}">${Number(r.min).toFixed(1)}</b><input data-min="${esc(a.id)}" type="range" min="0" max="10" step="0.5" value="${r.min}"></label><label>${t('personalRange')} max: <b data-max-label="${esc(a.id)}">${Number(r.max).toFixed(1)}</b><input data-max="${esc(a.id)}" type="range" min="0" max="10" step="0.5" value="${r.max}"></label></div><textarea data-comment="${esc(a.id)}" placeholder="${t('commentPlaceholder')}">${esc(r.comment||'')}</textarea></div></article>`}

function featureTabs(){const items=[['all',`${t('all')} (${SCHEDULE.length})`],['plan',`☆ ${t('myPlan')} (${state.plan.length})`],...STAGES.map(s=>[s,`${s} (${SCHEDULE.filter(a=>a.stage===s).length})`]),['indianSpirit',`🪶 ${t('indianSpirit')} (${IS_ACTS.size})`],['discover',t('discover')],['recommendations',t('recommendations')],['import',t('excelImport')],['routing',t('routing')],['first',t('first')]];$('#featureTabs').innerHTML=items.map(([id,label])=>`<button data-feature="${id}" class="${(id==='all'&&state.route==='schedule'&&state.stage==='all')||(STAGES.includes(id)&&state.route==='schedule'&&state.stage===id)||state.route===id?'active':''}">${label}</button>`).join('')}
function chrome(){const ui=UI_LABELS[state.lang];document.documentElement.lang=state.lang;document.body.classList.toggle('compact',state.compact);document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#language').value=state.lang;$('#language').ariaLabel=ui.language;$('#reminderButton').title=$('#reminderButton').ariaLabel=ui.reminders;$('#reminderButton').classList.toggle('active',state.reminders);$('#compactButton').title=$('#compactButton').ariaLabel=ui.compact;$('#infoButton').title=$('#infoButton').ariaLabel=ui.guide;$('#cacheButton').title=$('#cacheButton').ariaLabel=ui.cache;$('#featureTabs').ariaLabel=ui.areas;$('.bottom-nav').ariaLabel=ui.mainNav;document.querySelectorAll('.dialog-close').forEach(b=>b.ariaLabel=ui.close);$('#planCount').textContent=state.plan.length;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));featureTabs()}
function go(route){state.route=route;location.hash=route;render()}
function home(){return `<section class="hero"><div class="eyebrow">v5.0 · Offline PWA · Unofficial</div><h1>YOUR FESTIVAL.<br>YOUR FLOW.</h1><p>${t('disclaimer')}</p><div class="stats"><div class="stat"><b>${SCHEDULE.length}</b><small>${t('acts')}</small></div><div class="stat"><b>5</b><small>${t('stages')}</small></div><div class="stat"><b>${state.plan.length}</b><small>${t('saved')}</small></div><div class="stat"><b>${Object.keys(state.reviews).length}</b><small>${t('ratings')}</small></div></div></section><section class="quick-grid"><button class="quick hot" data-route="live"><span>●</span><strong>${t('liveNow')}</strong><small>${t('nextActs')}</small></button><button class="quick" data-route="schedule"><span>▦</span><strong>${t('schedule')}</strong><small>${SCHEDULE.length} ${t('acts')}</small></button><button class="quick discover" data-route="discover"><span>✦</span><strong>${t('discover')}</strong><small>${t('surprise')}</small></button><button class="quick recommend" data-route="recommendations"><span>◆</span><strong>${t('recommendations')}</strong><small>${t('forYou')}</small></button><button class="quick" data-route="plan"><span>☆</span><strong>${t('myPlan')}</strong><small>${state.plan.length} ${t('saved')}</small></button><button class="quick" data-route="routing"><span>↳</span><strong>${t('routing')}</strong><small>7+ · ${t('conflicts')}</small></button><button class="quick" data-route="first"><span>◎</span><strong>${t('first')}</strong><small>DON'T MISS · CORE · RESET</small></button><button class="quick" data-route="journal"><span>✎</span><strong>${t('journal')}</strong><small>${t('ratings')}</small></button></section><div class="section-head"><h2>${t('festival')}</h2></div><section class="festival-box"><div class="festival-step"><b>${t('arrival')}</b><small>${t('arrivalSub')}</small></div><div class="festival-step"><b>${t('preDays')}</b><small>${t('preDaysSub')}</small></div><div class="festival-step"><b>${t('openStages')}</b><small>${t('openStagesSub')}</small></div><div class="festival-step"><b>${t('closing')}</b><small>${t('closingSub')}</small></div></section><div class="section-head"><h2>${UI_LABELS[state.lang].opening}</h2></div><div class="timeline">${SCHEDULE.filter(a=>a.artist==='Opening Ceremony').map(card).join('')}</div>`}
function genreButtons(attribute='genre'){return `<div class="filter-row genre-row"><button data-${attribute}="all" class="${state.genre==='all'?'active':''}">${t('allGenres')}</button>${GENRES.map(genre=>`<button data-${attribute}="${esc(genre)}" class="${state.genre===genre?'active':''}">${esc(genre)}</button>`).join('')}</div>`}
function filters(){return `<div class="controls"><input id="search" class="search" type="search" value="${esc(state.search)}" placeholder="${t('search')}"><div class="filter-row">${['all',...DATES.map((_,i)=>String(i))].map(v=>`<button data-day="${v}" class="${String(state.day)===v?'active':''}">${v==='all'?t('allDays'):dateLabel(Number(v))}</button>`).join('')}</div>${genreButtons()}<div class="filter-row">${[[0,t('allActs')],[7,t('rating7')],[8,t('rating8')],[9,t('rating9')]].map(([v,l])=>`<button data-rating="${v}" class="${state.rating===v?'active':''}">${l}</button>`).join('')}</div></div>`}
function filtered(){const q=state.search.trim().toLocaleLowerCase();return SCHEDULE.filter(a=>(state.day==='all'||a.day===Number(state.day))&&(state.stage==='all'||a.stage===state.stage)&&(state.genre==='all'||a.genre===state.genre)&&score(a.id)>=state.rating&&(!q||`${a.artist} ${a.stage} ${a.genre} ${a.type}`.toLocaleLowerCase().includes(q)))}
function grouped(list){const days=[...new Set(list.map(a=>a.day))];return days.map(d=>`<section class="day-group"><h2>${dateLabel(d)}</h2><div class="timeline">${list.filter(a=>a.day===d).map(a=>card(a)).join('')}</div></section>`).join('')}
function posters(){return `<div class="poster-row">${POSTERS.map(([n,f])=>`<a href="${f}?v=500" target="_blank" rel="noopener"><img src="${f}?v=500" alt="${n}"><b>${n}</b></a>`).join('')}</div>`}
function schedule(){const list=filtered();return `<div class="section-head"><div><h1>${state.stage==='all'?t('schedule'):state.stage}</h1><p>${list.length} ${t('acts')}</p></div></div>${filters()}${list.length?grouped(list):`<div class="empty">${t('allActs')}: 0</div>`}<div class="section-head"><h2>${t('posters')}</h2></div>${posters()}`}
function plan(){const list=state.plan.map(id=>SCHEDULE.find(a=>a.id===id)).filter(Boolean).sort((a,b)=>a.day-b.day||mins(a.start)-mins(b.start));return `<div class="section-head"><div><h1>☆ ${t('myPlan')}</h1><p>${list.length} ${t('saved')}</p></div><div class="plan-actions"><button class="secondary" id="sharePlan">${t('share')}</button><button class="danger" id="clearPlan">${t('clearAll')}</button></div></div>${list.length?grouped(list):`<div class="empty">${t('emptyPlan')}</div>`}`}
function journal(){const list=SCHEDULE.filter(a=>state.reviews[a.id]||state.plan.includes(a.id));return `<div class="section-head"><div><h1>✎ ${t('journal')}</h1><p>${list.length} ${t('acts')}</p></div></div>${list.length?grouped(list.map(a=>a)):`<div class="empty">${t('emptyPlan')}</div>`}`}
function live(){const now=new Date(),live=LIVE_SCHEDULE.filter(a=>now>=startDate(a)&&now<endDate(a));const next=STAGES.map(stage=>LIVE_SCHEDULE.filter(a=>a.stage===stage&&startDate(a)>now).sort((a,b)=>startDate(a)-startDate(b))[0]).filter(Boolean);return `<div class="section-head"><div><h1>● ${t('liveNow')}</h1><p id="liveClock">${new Intl.DateTimeFormat(state.lang,{dateStyle:'medium',timeStyle:'short'}).format(now)}</p></div></div>${live.length?`<div class="timeline">${live.map(card).join('')}</div>`:`<div class="empty">${t('nothingLive')}</div>`}<div class="section-head"><h2>${t('nextActs')}</h2></div>${next.length?`<div class="timeline">${next.map(card).join('')}</div>`:`<div class="empty">${t('nothingLive')}</div>`}`}
function hashValue(value){let hash=2166136261;for(const char of value){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return hash>>>0}
function discoveryPool(){return SCHEDULE.filter(a=>!state.plan.includes(a.id)&&!state.reviews[a.id]&&(state.genre==='all'||a.genre===state.genre)).sort((a,b)=>hashValue(`${b.id}-${state.discoverySeed}`)-hashValue(`${a.id}-${state.discoverySeed}`)).slice(0,12)}
function discover(){const now=new Date(),active=LIVE_SCHEDULE.filter(a=>(now>=startDate(a)&&now<endDate(a))||(startDate(a)>now&&startDate(a)-now<=3*60*60*1000)).filter(a=>state.genre==='all'||a.genre===state.genre).slice(0,10),mix=discoveryPool();return `<div class="section-head"><div><h1>✦ ${t('discover')}</h1><p>${t('discoverIntro')}</p></div><button class="primary" id="newMix">↻ ${t('newMix')}</button></div><div class="controls">${genreButtons('discover-genre')}</div>${active.length?`<div class="section-head"><h2>${t('liveNow')} · ${t('nextActs')}</h2></div><div class="timeline">${active.map(card).join('')}</div>`:''}<div class="section-head"><div><h2>${t('surprise')}</h2><p>${mix.length} ${t('acts')}</p></div></div>${mix.length?grouped(mix):`<div class="empty">${t('allActs')}: 0</div>`}`}
function preferenceProfile(){const liked=SCHEDULE.filter(a=>state.plan.includes(a.id)||(state.reviews[a.id]&&score(a.id)>=7)),genres={},stages={};for(const act of liked){const weight=Math.max(1,score(act.id)||7);genres[act.genre]=(genres[act.genre]||0)+weight;stages[act.stage]=(stages[act.stage]||0)+weight}return {liked,genres,stages}}
function recommendationFit(act,profile){return (profile.genres[act.genre]||0)*3+(profile.stages[act.stage]||0)*1.5+(IS_ACTS.has(act.artist)?4:0)+(state.reviews[act.id]?score(act.id):0)}
function recommendationItem(act,fit,profile){const reasons=[];if(profile.genres[act.genre])reasons.push(`${t('basedOnGenre')}: ${act.genre}`);if(profile.stages[act.stage])reasons.push(`${t('basedOnStage')}: ${act.stage}`);if(IS_ACTS.has(act.artist))reasons.push('🪶 IS');const percent=Math.min(99,Math.round(55+fit/4));return `<section class="recommendation-item"><div class="recommendation-reason"><b>${profile.liked.length?`${percent}% ${t('match')}`:t('curated')}</b><small>${reasons.join(' · ')||t('curated')}</small></div>${card(act)}</section>`}
function recommendations(){const profile=preferenceProfile(),curatedNames=[...FIRST.dont,...FIRST.core,...FIRST.reset],curatedActs=curatedNames.map(name=>SCHEDULE.find(a=>a.artist===name)).filter(Boolean),candidates=SCHEDULE.filter(a=>!state.plan.includes(a.id)),ranked=profile.liked.length?candidates.map(act=>({act,fit:recommendationFit(act,profile)})).sort((a,b)=>b.fit-a.fit||startDate(a.act)-startDate(b.act)).slice(0,12):curatedActs.slice(0,12).map(act=>({act,fit:0}));return `<div class="section-head"><div><h1>◆ ${t('recommendations')}</h1><p>${t('recommendIntro')}</p></div></div>${profile.liked.length?'':`<p class="notice">${t('noPreferences')}</p>`}<div class="recommendation-list">${ranked.map(item=>recommendationItem(item.act,item.fit,profile)).join('')}</div>`}
function overlaps(list){const pairs=[];for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(a.day===b.day&&a.stage!==b.stage&&startDate(a)<endDate(b)&&startDate(b)<endDate(a))pairs.push([a,b])}return pairs.sort((x,y)=>Math.max(score(y[0].id),score(y[1].id))-Math.max(score(x[0].id),score(x[1].id)))}
function routing(){
  const list=SCHEDULE.filter(a=>score(a.id)>=7);
  const pairs=overlaps(list);
  const days=[...new Set(list.map(a=>a.day))];
  const conflictMarkup=pairs.length
    ? `<div class="section-head"><h2>${t('conflicts')}</h2></div>${pairs.slice(0,5).map(([a,b])=>`<div class="conflict"><strong>${dateLabel(a.day)} · ${a.start}</strong><div>${a.artist} (${ratingText(a.id)})</div><div>↳ ${t('alternative')}: ${b.artist} (${ratingText(b.id)})</div><small>${t('recommendation')}: ${score(a.id)>=score(b.id)?a.artist:b.artist}</small></div>`).join('')}`
    : '';
  const dayMarkup=days.length
    ? days.map(d=>`<section class="route-day"><h2>${dateLabel(d)}</h2>${list.filter(a=>a.day===d).map(a=>card(a)).join('')}</section>`).join('')
    : `<div class="empty">${t('emptyRating')}</div>`;
  return `<div class="section-head"><div><h1>↳ ${t('routing')}</h1><p>7+ · ${list.length} ${t('acts')}</p></div></div>${conflictMarkup}${dayMarkup}`;
}
function pickGroup(kind,names){const items=names.map(n=>SCHEDULE.find(a=>a.artist===n)).filter(Boolean);return `<article class="first-card"><h3 class="${kind}">${t(kind==='dont'?'dontMiss':kind)}</h3>${items.map(a=>`<div><b>${a.artist}</b><div class="meta">${dateLabel(a.day)} · ${a.start} · ${a.stage}${IS_ACTS.has(a.artist)?' · 🪶 IS':''}</div></div>`).join('')}</article>`}
function first(){return `<div class="section-head"><div><h1>${t('first')}</h1><p>${t('firstIntro')}</p></div><button class="primary" data-route="schedule">${t('all')} ${SCHEDULE.length} ${t('acts')}</button></div><div class="first-grid">${pickGroup('dont',FIRST.dont)}${pickGroup('core',FIRST.core)}${pickGroup('reset',FIRST.reset)}</div><p class="notice">${t('credit')}</p><div class="section-head"><h2>Ambyss / Y2KZERO</h2></div><p class="notice">${t('missingAmbyss')}</p><div class="section-head"><h2>${t('posters')}</h2></div>${posters()}`}
function indianSpirit(){const list=SCHEDULE.filter(act=>IS_ACTS.has(act.artist));return `<div class="section-head"><div><h1>🪶 ${t('indianSpirit')} 2026</h1><p>${t('isIntro')}</p></div><span class="is-count">${IS_ACTS.size}</span></div><p class="notice is-source">${t('isSource')}</p>${grouped(list)}`}
function importableRecords(){return (state.importPreview?.records||[]).filter(record=>record.min!=null||record.max!=null||record.comment||record.youtube||record.spotify||record.plan)}
function importPreviewMarkup(){const preview=state.importPreview;if(!preview)return '';if(preview.error)return `<p class="notice danger-note">${t('importError')} ${esc(preview.error)}</p>`;const usable=importableRecords(),recognized=preview.recognizedRows??preview.records.length;return `<section class="import-result"><h2>${t('importReady')}</h2><p><b>${esc(preview.fileName)}</b></p><div class="import-stats"><span><b>${recognized}</b>${t('recognizedRows')}</span><span><b>${usable.length}</b>${t('matchedActs')}</span><span><b>${preview.unmatched.length}</b>${t('unmatchedArtists')}</span></div>${preview.unmatched.length?`<details><summary>${t('unmatchedArtists')}</summary><p>${preview.unmatched.map(esc).join(' · ')}</p></details>`:''}${usable.length?`<button class="primary" id="applyExcelImport">${t('applyImport')}</button>`:`<p class="notice">${t(recognized?'noPersonalData':'noImportData')}</p>`}</section>`}
function excelImport(){return `<div class="section-head"><div><h1>▦ ${t('excelImport')}</h1><p>${t('importIntro')}</p></div></div><section class="import-panel"><div class="import-icon">XLSX</div><div><h2>${t('chooseExcel')}</h2><p>${t('importSupports')}</p><p class="meta">🔒 ${t('importPrivacy')}</p></div><label class="primary file-button">${t('chooseExcel')}<input id="excelFile" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></label></section><a class="template-download" href="Ozora-2026-Import-Template.xlsx?v=500" download>↓ ${t('downloadTemplate')}</a><p class="notice">${t('templateHint')}</p>${importPreviewMarkup()}`}
function homeTools(){return `<section class="quick-grid home-tools"><button class="quick is-quick" data-route="indianSpirit"><span>🪶</span><strong>${t('indianSpirit')}</strong><small>${IS_ACTS.size} ${t('acts')}</small></button><button class="quick import-quick" data-route="import"><span>▦</span><strong>${t('excelImport')}</strong><small>${t('personalData')}</small></button></section>`}
function sharePanel(){return `<section class="share-panel"><div><span class="share-icon">▦</span><div><h2>${t('shareTitle')}</h2><p>${t('scanToShare')}</p></div></div><button class="primary" data-open-qr>${t('showQr')}</button></section>`}
function render(){chrome();const views={home,schedule,discover,recommendations,plan,journal,live,routing,first,indianSpirit,import:excelImport};$('#app').innerHTML=(views[state.route]||home)();if(state.route==='home'){$('.hero .eyebrow').textContent='v5.0 · Offline PWA · Unofficial';$('#app').insertAdjacentHTML('beforeend',homeTools()+sharePanel())}bind()}

function bind(){
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
  document.querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>{const v=b.dataset.feature;if(v==='all'){state.stage='all';state.day='all';state.genre='all';state.rating=0;state.search='';go('schedule')}else if(STAGES.includes(v)){state.stage=v;go('schedule')}else go(v)});
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=b.dataset.day;render()});
  document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{state.genre=b.dataset.genre;render()});
  document.querySelectorAll('[data-discover-genre]').forEach(b=>b.onclick=()=>{state.genre=b.dataset.discoverGenre;render()});
  document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{state.rating=Number(b.dataset.rating);render()});
  const search=$('#search');if(search)search.oninput=e=>{const value=e.target.value;state.search=value;render();const next=$('#search');next.focus();next.setSelectionRange(value.length,value.length)};
  document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save,i=state.plan.indexOf(id);i<0?state.plan.push(id):state.plan.splice(i,1);persist();toast(t(i<0?'added':'removed'));render()});
  document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>document.querySelector(`[data-card="${b.dataset.detail}"]`)?.classList.toggle('open'));
  document.querySelectorAll('[data-min]').forEach(el=>{el.oninput=e=>saveRange(e.target.dataset.min,'min',Number(e.target.value));el.onchange=e=>saveRange(e.target.dataset.min,'min',Number(e.target.value),true)});
  document.querySelectorAll('[data-max]').forEach(el=>{el.oninput=e=>saveRange(e.target.dataset.max,'max',Number(e.target.value));el.onchange=e=>saveRange(e.target.dataset.max,'max',Number(e.target.value),true)});
  document.querySelectorAll('[data-comment]').forEach(el=>el.onchange=e=>{const id=e.target.dataset.comment;state.reviews[id]={...review(id),comment:e.target.value};persist()});
  document.querySelectorAll('[data-artist]').forEach(b=>b.onclick=()=>showArtist(b.dataset.artist));
  document.querySelectorAll('[data-open-qr]').forEach(b=>b.onclick=openQR);
  const excelFile=$('#excelFile');if(excelFile)excelFile.onchange=event=>handleExcelFile(event.target.files?.[0]);
  const applyExcel=$('#applyExcelImport');if(applyExcel)applyExcel.onclick=applyExcelImport;
  const newMix=$('#newMix');if(newMix)newMix.onclick=()=>{state.discoverySeed+=1;render()};
  const share=$('#sharePlan');if(share)share.onclick=sharePlan;const clear=$('#clearPlan');if(clear)clear.onclick=()=>{if(confirm(t('confirmClear'))){state.plan=[];persist();render()}};
}
document.addEventListener('click',event=>{
  const quick=event.target.closest('[data-quick-rating]');
  if(quick){event.preventDefault();saveSingleRating(quick.dataset.quickRating,Number(quick.dataset.value));return}
  const trigger=event.target.closest('[data-rate]');
  if(trigger){event.preventDefault();document.querySelector(`[data-card="${trigger.dataset.rate}"]`)?.classList.toggle('open')}
});
async function handleExcelFile(file){if(!file)return;try{state.importPreview=await window.OZORA_XLSX_IMPORT.parseFile(file,SCHEDULE);render()}catch(error){state.importPreview={error:error.message||String(error),fileName:file.name,records:[],unmatched:[]};render()}}
function applyExcelImport(){const records=importableRecords();for(const record of records){const current={...review(record.id)};if(record.min!=null){current.min=Math.max(0,Math.min(10,Number(record.min)));current.max=Math.max(current.min,Math.min(10,Number(record.max??record.min)))}if(record.comment)current.comment=record.comment;if(record.youtube)current.youtube=record.youtube;if(record.spotify)current.spotify=record.spotify;state.reviews[record.id]=current;if(record.plan&&!state.plan.includes(record.id))state.plan.push(record.id)}persist();toast(t('importDone'));state.importPreview={...state.importPreview,records:[]};render()}
function updateRatingUI(id){const r=review(id),card=document.querySelector(`[data-card="${id}"]`);if(card){const badge=card.querySelector('.rating-badge'),min=card.querySelector('[data-min]'),max=card.querySelector('[data-max]'),minLabel=card.querySelector('[data-min-label]'),maxLabel=card.querySelector('[data-max-label]');if(badge)badge.textContent=ratingText(id);if(min)min.value=r.min;if(max)max.value=r.max;if(minLabel)minLabel.textContent=Number(r.min).toFixed(1);if(maxLabel)maxLabel.textContent=Number(r.max).toFixed(1);card.querySelectorAll('[data-quick-rating]').forEach(button=>button.classList.toggle('selected',Number(r.min)===Number(button.dataset.value)&&Number(r.max)===Number(button.dataset.value)));card.classList.toggle('epic',score(id)>=9)}document.querySelectorAll(`[data-profile-rating-label="${id}"]`).forEach(label=>label.textContent=ratingText(id));document.querySelectorAll(`[data-profile-act="${id}"] [data-quick-rating]`).forEach(button=>button.classList.toggle('selected',Number(r.min)===Number(button.dataset.value)&&Number(r.max)===Number(button.dataset.value)))}
function saveRange(id,key,value,notify=false){const r={...review(id),[key]:value};if(r.min>r.max){if(key==='min')r.max=r.min;else r.min=r.max}state.reviews[id]=r;persist();updateRatingUI(id);if(notify)toast(t('ratingSaved'))}
function saveSingleRating(id,value){state.reviews[id]={...review(id),min:value,max:value};persist();const card=document.querySelector(`[data-card="${id}"]`);if(card)card.classList.add('open');updateRatingUI(id);toast(t('ratingSaved'))}
function profileOccurrence(a){const r=review(a.id);return `<section class="profile-occurrence" data-profile-act="${esc(a.id)}"><div class="profile-occurrence-head"><div><b>${dateLabel(a.day)} · ${a.start}–${a.end}</b><small>${esc(a.stage)}</small></div><span class="profile-rating-label" data-profile-rating-label="${esc(a.id)}">${ratingText(a.id)}</span></div><div class="profile-score-grid" role="group" aria-label="${t('rateAct')}">${[0,1,2,3,4,5,6,7,8,9,10].map(value=>`<button data-quick-rating="${esc(a.id)}" data-value="${value}" class="${Number(r.min)===value&&Number(r.max)===value?'selected':''}" aria-label="${t('rateAct')}: ${value}">${value}</button>`).join('')}</div></section>`}
function showArtist(name){const occurrences=SCHEDULE.filter(a=>a.artist===name),l=links(name);$('#artistContent').innerHTML=`<div class="eyebrow">${UI_LABELS[state.lang].artist}</div><h2>${esc(name)}</h2>${IS_ACTS.has(name)?'<p><span class="tag is">🪶 Indian Spirit</span></p>':''}<div class="profile-links"><a href="${l.YouTube}" target="_blank" rel="noopener">▶ YouTube</a><a href="${l.Spotify}" target="_blank" rel="noopener">♫ Spotify</a></div><h3>${t('rateAct')}</h3><p class="profile-rating-hint">${t('rateHint')}</p><div class="profile-occurrences">${occurrences.map(profileOccurrence).join('')}</div>`;$('#artistDialog').showModal()}
function qrMarkup(){return `<div class="eyebrow">OZORA 2026</div><h2>${t('shareTitle')}</h2><p>${t('scanToShare')}</p><img src="qr-code.png?v=500" alt="QR-Code: ${APP_URL}"><a class="app-url" href="${APP_URL}" target="_blank" rel="noopener">${APP_URL}</a><div class="qr-actions"><button class="secondary" id="copyAppLink">${t('copyLink')}</button><button class="primary" id="shareAppLink">${t('shareLink')}</button></div><p class="donation-note">${t('donationNote')}</p>`}
function openQR(){$('#qrContent').innerHTML=qrMarkup();$('#copyAppLink').onclick=copyAppLink;$('#shareAppLink').onclick=shareAppLink;if(!$('#qrDialog').open)$('#qrDialog').showModal()}
async function copyAppLink(){let copied=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(APP_URL);copied=true}}catch{}if(!copied){const field=document.createElement('textarea');field.value=APP_URL;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();try{copied=document.execCommand('copy')}catch{}field.remove()}toast(copied?t('linkCopied'):APP_URL)}
async function shareAppLink(){try{if(navigator.share)await navigator.share({title:'Ozora 2026 Festival Planner',text:t('shareText'),url:APP_URL});else await copyAppLink()}catch(error){if(error.name!=='AbortError')await copyAppLink()}}
function reminderMarkup(){const permission='Notification'in window?Notification.permission:'unsupported';return `<div class="eyebrow">OZORA 2026</div><h2>🔔 ${t('reminders')}</h2><div class="reminder-status ${state.reminders?'on':'off'}"><b>${t(state.reminders?'reminderOn':'reminderOff')}</b><small>${state.plan.length} ${t('saved')}</small></div><label class="reminder-select">${t('reminderBefore')}<select id="reminderMinutes">${[5,10,15,30].map(value=>`<option value="${value}" ${state.reminderMinutes===value?'selected':''}>${value}</option>`).join('')}</select></label><button class="primary reminder-toggle" id="toggleReminders">${t(state.reminders?'disableReminders':'enableReminders')}</button><p class="notice reminder-note">${t('reminderLimit')}</p>${permission==='denied'?`<p class="notice danger-note">${t('notificationBlocked')}</p>`:''}`}
function openReminders(){$('#reminderContent').innerHTML=reminderMarkup();$('#reminderMinutes').onchange=e=>{state.reminderMinutes=Number(e.target.value);state.notified={};persist();toast(t('reminderSaved'))};$('#toggleReminders').onclick=toggleReminders;if(!$('#reminderDialog').open)$('#reminderDialog').showModal()}
async function toggleReminders(){
  if(state.reminders){state.reminders=false;persist();chrome();openReminders();return}
  if(!('Notification'in window)){toast(t('notificationUnsupported'));return}
  const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();
  if(permission!=='granted'){toast(t('notificationBlocked'));openReminders();return}
  state.reminders=true;state.notified={};persist();chrome();openReminders();checkReminders();
}
async function showActReminder(act){const body=`${act.stage} · ${act.start} · ${act.artist} ${t('startsSoon')}`;const options={body,icon:'./icon-192.png?v=500',badge:'./icon-192.png?v=500',tag:`ozora-${act.id}`,data:{route:'plan'}};try{if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.ready;await registration.showNotification(act.artist,options)}else new Notification(act.artist,options)}catch(error){console.warn('Reminder could not be shown',error)}}
function checkReminders(now=new Date()){
  if(!state.reminders||!('Notification'in window)||Notification.permission!=='granted')return;
  for(const id of state.plan){const act=SCHEDULE.find(item=>item.id===id);if(!act)continue;const delta=(startDate(act)-now)/60000,key=`${act.id}-${state.reminderMinutes}`;if(delta>0&&delta<=state.reminderMinutes&&!state.notified[key]){state.notified[key]=Date.now();persist();showActReminder(act)}}
}
async function sharePlan(){const text=state.plan.map(id=>SCHEDULE.find(a=>a.id===id)).filter(Boolean).sort((a,b)=>a.day-b.day||mins(a.start)-mins(b.start)).map(a=>`${dateLabel(a.day)} ${a.start} ${a.artist} — ${a.stage}`).join('\n');try{if(navigator.share)await navigator.share({title:'My Ozora 2026 Plan',text});else{await navigator.clipboard.writeText(text);toast(t('copied'))}}catch(error){if(error.name!=='AbortError')console.error(error)}}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function instructions(){const tr=I18N[state.lang],heads=['intro','install','navigation','planHelp','ratingHelp','liveHelp','routingHelp','offline','privacy'];$('#infoContent').innerHTML=`<h2>${t('helpTitle')}</h2>${heads.map((h,i)=>`<section class="help-section"><h3>${i+1}. ${t(h)}</h3><p>${tr.helpTexts[i]}</p></section>`).join('')}`}
async function clearCache(){if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}toast(t('clearCache'));setTimeout(()=>location.reload(),700)}

$('#language').onchange=e=>{state.lang=e.target.value;persist();render()};
$('#reminderButton').onclick=openReminders;
$('#compactButton').onclick=()=>{state.compact=!state.compact;persist();render()};
$('#infoButton').onclick=()=>{instructions();$('#infoDialog').showModal()};
$('#cacheButton').onclick=clearCache;
$('#qrButton').onclick=openQR;
$('#kofiLink').href=KOFI_URL;
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('selected',x===b));persist();chrome()});
$('#introContinue').onclick=()=>{localStorage.ozIntroSeen='1';$('#introDialog').close();render();instructions();$('#infoDialog').showModal()};
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const reg=await navigator.serviceWorker.register('./service-worker.js?v=500',{updateViaCache:'none'});reg.update();checkReminders();if(localStorage.ozIntroSeen!=='1')$('#introDialog').showModal()});
setInterval(()=>{checkReminders();if(['live','schedule','discover'].includes(state.route))render()},60000);
render();
