const DATA={
 artists:{
  "Ace Ventura":{genre:"Progressive",country:"IL",links:{Spotify:"https://open.spotify.com/search/Ace%20Ventura%20psytrance",YouTube:"https://www.youtube.com/results?search_query=Ace+Ventura+psytrance",SoundCloud:"https://soundcloud.com/search?q=Ace%20Ventura"}},
  "Atmos":{genre:"Progressive",country:"SE",links:{Spotify:"https://open.spotify.com/search/Atmos%20psytrance",YouTube:"https://www.youtube.com/results?search_query=Atmos+psytrance"}},
  "Astrix":{genre:"Psytrance",country:"IL",links:{Spotify:"https://open.spotify.com/search/Astrix",YouTube:"https://www.youtube.com/results?search_query=Astrix+live"}},
  "Carbon Based Lifeforms":{genre:"Downtempo",country:"SE",links:{Spotify:"https://open.spotify.com/search/Carbon%20Based%20Lifeforms",YouTube:"https://www.youtube.com/results?search_query=Carbon+Based+Lifeforms"}},
  "Grouch":{genre:"Psybass",country:"NZ",links:{SoundCloud:"https://soundcloud.com/search?q=Grouch",YouTube:"https://www.youtube.com/results?search_query=Grouch+psy"}},
  "Liquid Soul":{genre:"Progressive",country:"CH",links:{Spotify:"https://open.spotify.com/search/Liquid%20Soul",YouTube:"https://www.youtube.com/results?search_query=Liquid+Soul+live"}},
  "Merkaba":{genre:"Psybass",country:"AU",links:{Spotify:"https://open.spotify.com/search/Merkaba",SoundCloud:"https://soundcloud.com/search?q=Merkaba"}},
  "Parasense":{genre:"Forest",country:"RU",links:{YouTube:"https://www.youtube.com/results?search_query=Parasense+psytrance"}},
  "Pantomiman":{genre:"Full-On",country:"RU",links:{YouTube:"https://www.youtube.com/results?search_query=Pantomiman+live"}},
  "Solar Fields":{genre:"Ambient",country:"SE",links:{Spotify:"https://open.spotify.com/search/Solar%20Fields",YouTube:"https://www.youtube.com/results?search_query=Solar+Fields"}}
 },
 schedule:[
  {id:"a1",day:0,start:"10:00",end:"11:30",artist:"Atmos",stage:"Dome",type:"Live"},{id:"a2",day:0,start:"11:15",end:"12:45",artist:"Pantomiman",stage:"Ozora",type:"Live"},{id:"a3",day:0,start:"13:00",end:"14:30",artist:"Liquid Soul",stage:"Ozora",type:"DJ Set"},{id:"a4",day:0,start:"15:00",end:"16:30",artist:"Grouch",stage:"Dragon",type:"Live"},{id:"a5",day:0,start:"18:00",end:"19:30",artist:"Solar Fields",stage:"Dome",type:"Live"},
  {id:"b1",day:1,start:"09:30",end:"11:00",artist:"Carbon Based Lifeforms",stage:"Dome",type:"Live"},{id:"b2",day:1,start:"12:00",end:"13:30",artist:"Merkaba",stage:"Dragon",type:"Live"},{id:"b3",day:1,start:"14:00",end:"15:30",artist:"Ace Ventura",stage:"Ozora",type:"DJ Set"},{id:"b4",day:1,start:"16:00",end:"17:30",artist:"Parasense",stage:"Pumpui",type:"Live"},{id:"b5",day:1,start:"20:00",end:"22:00",artist:"Astrix",stage:"Ozora",type:"DJ Set"},
  {id:"c1",day:2,start:"11:00",end:"12:30",artist:"Solar Fields",stage:"Dome",type:"Live"},{id:"c2",day:2,start:"13:00",end:"14:30",artist:"Atmos",stage:"Ozora",type:"DJ Set"},{id:"c3",day:2,start:"15:00",end:"16:30",artist:"Merkaba",stage:"Dragon",type:"Live"},{id:"c4",day:2,start:"18:00",end:"19:30",artist:"Pantomiman",stage:"Pumpui",type:"Live"}
 ], days:["MON","TUE","WED"], stages:{Ozora:"#ff5a78",Dome:"#ffc857",Dragon:"#51d6c4",Pumpui:"#a985ff"}
};
const I18N={
 de:{navHome:"Start",navSchedule:"Zeitplan",navDiscover:"Entdecken",navPlan:"Mein Plan",navJournal:"Tagebuch",welcome:"DEIN FESTIVAL. DEIN FLOW.",hero:"Alles, was du für deine Tage brauchst – schnell, persönlich und offline.",acts:"Acts",saved:"gespeichert",journal:"Einträge",now:"Was läuft jetzt?",nowSub:"Direkt zum aktuellen Programm",discover:"Entdecken",discoverSub:"Neue Sounds für deinen Tag",plan:"Mein Plan",planSub:"Deine persönliche Timeline",recommend:"Empfehlungen",recommendSub:"Passend zu deinem Geschmack",today:"Heute im Blick",all:"Alle",schedule:"Zeitplan",scheduleSub:"Nach Tag und Genre filtern",emptyPlan:"Noch keine Acts gespeichert.",emptyJournal:"Speichere zuerst Acts in deinem Plan.",forYou:"Für dich empfohlen",forYouSub:"Basierend auf deinen gespeicherten Genres",openProfile:"Künstlerprofil öffnen",country:"Herkunft",remindersOn:"Erinnerungen aktiviert",remindersOff:"Erinnerungen sind nicht verfügbar",savedToast:"Zum Plan hinzugefügt",removedToast:"Aus dem Plan entfernt",notes:"Deine Erinnerung an diesen Moment …",save:"Speichern",journalTitle:"Festival-Tagebuch",journalSub:"Bewerte deine gespeicherten Acts und halte Momente fest.",permission:"Browser-Erinnerungen",permissionHelp:"Erinnerungen werden geprüft, solange die App geöffnet ist. Geschlossene Browser können ohne Push-Dienst keine verlässlichen Alarme auslösen.",enable:"Aktivieren",noMatch:"Keine Acts für diesen Filter.",demo:"Beispielprogramm – ersetze die Daten in assets/app.js durch den finalen Spielplan.",language:"Sprache",notification:"Erinnerungen",homeLabel:"Startseite",close:"Schließen"},
 en:{navHome:"Home",navSchedule:"Schedule",navDiscover:"Discover",navPlan:"My Plan",navJournal:"Journal",welcome:"YOUR FESTIVAL. YOUR FLOW.",hero:"Everything you need for your days – fast, personal and offline.",acts:"Acts",saved:"saved",journal:"entries",now:"What’s on now?",nowSub:"Jump to the current programme",discover:"Discover",discoverSub:"New sounds for your day",plan:"My Plan",planSub:"Your personal timeline",recommend:"Recommendations",recommendSub:"Matched to your taste",today:"Today at a glance",all:"All",schedule:"Schedule",scheduleSub:"Filter by day and genre",emptyPlan:"No acts saved yet.",emptyJournal:"Save acts to your plan first.",forYou:"Recommended for you",forYouSub:"Based on your saved genres",openProfile:"Open artist profile",country:"From",remindersOn:"Reminders enabled",remindersOff:"Reminders are unavailable",savedToast:"Added to your plan",removedToast:"Removed from your plan",notes:"Your memory of this moment …",save:"Save",journalTitle:"Festival journal",journalSub:"Rate saved acts and capture the moments.",permission:"Browser reminders",permissionHelp:"Reminders are checked while the app is open. Closed browsers cannot deliver reliable alarms without a push service.",enable:"Enable",noMatch:"No acts match this filter.",demo:"Sample programme – replace the data in assets/app.js with the final schedule.",language:"Language",notification:"Reminders",homeLabel:"Home",close:"Close"},
 es:{navHome:"Inicio",navSchedule:"Horario",navDiscover:"Descubrir",navPlan:"Mi plan",navJournal:"Diario",welcome:"TU FESTIVAL. TU RITMO.",hero:"Todo lo que necesitas para tus días: rápido, personal y sin conexión.",acts:"Artistas",saved:"guardados",journal:"entradas",now:"¿Qué suena ahora?",nowSub:"Ir al programa actual",discover:"Descubrir",discoverSub:"Nuevos sonidos para tu día",plan:"Mi plan",planSub:"Tu agenda personal",recommend:"Recomendaciones",recommendSub:"Según tus gustos",today:"Hoy de un vistazo",all:"Todos",schedule:"Horario",scheduleSub:"Filtrar por día y género",emptyPlan:"Aún no has guardado actuaciones.",emptyJournal:"Primero guarda actuaciones en tu plan.",forYou:"Recomendado para ti",forYouSub:"Basado en tus géneros guardados",openProfile:"Abrir perfil del artista",country:"Origen",remindersOn:"Recordatorios activados",remindersOff:"Los recordatorios no están disponibles",savedToast:"Añadido a tu plan",removedToast:"Eliminado de tu plan",notes:"Tu recuerdo de este momento…",save:"Guardar",journalTitle:"Diario del festival",journalSub:"Valora tus actuaciones guardadas y conserva tus momentos.",permission:"Recordatorios del navegador",permissionHelp:"Los recordatorios se comprueban mientras la aplicación está abierta. Sin un servicio push, un navegador cerrado no ofrece alarmas fiables.",enable:"Activar",noMatch:"No hay actuaciones con este filtro.",demo:"Programa de ejemplo: sustituye los datos de assets/app.js por el horario definitivo.",language:"Idioma",notification:"Recordatorios",homeLabel:"Inicio",close:"Cerrar"},
 hu:{navHome:"Kezdőlap",navSchedule:"Program",navDiscover:"Felfedezés",navPlan:"Tervem",navJournal:"Napló",welcome:"A TE FESZTIVÁLOD. A TE RITMUSOD.",hero:"Minden, amire a napjaidhoz szükséged van – gyorsan, személyre szabva és offline.",acts:"Fellépők",saved:"mentve",journal:"bejegyzés",now:"Mi megy most?",nowSub:"Ugrás az aktuális programhoz",discover:"Felfedezés",discoverSub:"Új hangzások a napodhoz",plan:"Tervem",planSub:"Személyes idővonalad",recommend:"Ajánlások",recommendSub:"Az ízlésedhez igazítva",today:"Mai áttekintés",all:"Mind",schedule:"Program",scheduleSub:"Szűrés nap és műfaj szerint",emptyPlan:"Még nincs mentett fellépő.",emptyJournal:"Először ments fellépőket a tervedbe.",forYou:"Neked ajánljuk",forYouSub:"A mentett műfajaid alapján",openProfile:"Előadó profiljának megnyitása",country:"Származás",remindersOn:"Emlékeztetők bekapcsolva",remindersOff:"Az emlékeztetők nem érhetők el",savedToast:"Hozzáadva a tervedhez",removedToast:"Eltávolítva a tervedből",notes:"Emléked erről a pillanatról…",save:"Mentés",journalTitle:"Fesztiválnapló",journalSub:"Értékeld a mentett fellépőket, és örökítsd meg a pillanatokat.",permission:"Böngészős emlékeztetők",permissionHelp:"Az emlékeztetőket az alkalmazás nyitott állapotban ellenőrzi. Push szolgáltatás nélkül a bezárt böngésző nem tud megbízható riasztást küldeni.",enable:"Bekapcsolás",noMatch:"Nincs a szűrőnek megfelelő fellépő.",demo:"Mintaprogram – cseréld le az assets/app.js adatait a végleges programra.",language:"Nyelv",notification:"Emlékeztetők",homeLabel:"Kezdőlap",close:"Bezárás"}
};
const DAY_LABELS={de:["MO","DI","MI"],en:["MON","TUE","WED"],es:["LUN","MAR","MIÉ"],hu:["HÉT","KED","SZE"]};
let state={route:location.hash.slice(1)||"home",lang:localStorage.ozLang||"de",day:0,genre:"All",plan:JSON.parse(localStorage.ozPlan||"[]"),journal:JSON.parse(localStorage.ozJournal||"{}")};
const $=s=>document.querySelector(s),t=k=>I18N[state.lang][k]||k,artist=id=>DATA.artists[id],actById=id=>DATA.schedule.find(a=>a.id===id);
function persist(){localStorage.ozPlan=JSON.stringify(state.plan);localStorage.ozJournal=JSON.stringify(state.journal);updateChrome()}
function updateChrome(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));$("#language").value=state.lang;$("#language").ariaLabel=t('language');$("#notificationButton").ariaLabel=t('notification');$(".brand").ariaLabel=t('homeLabel');$(".dialog-close").ariaLabel=t('close');$(".bottom-nav").ariaLabel={de:'Hauptnavigation',en:'Main navigation',es:'Navegación principal',hu:'Fő navigáció'}[state.lang];$("#planCount").textContent=state.plan.length;document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.route===state.route))}
function go(route){state.route=route;location.hash=route;render()}
function card(a){const p=artist(a.artist),saved=state.plan.includes(a.id);return `<article class="act-card"><div class="time">${a.start}<div class="meta">${a.end}</div></div><i class="stage-line" style="background:${DATA.stages[a.stage]}"></i><div><button class="artist-link" data-artist="${a.artist}">${a.artist}</button><div class="meta">${a.stage} · ${p.genre} · ${a.type}</div></div><button class="heart ${saved?'saved':''}" data-save="${a.id}" aria-label="${t('plan')}">${saved?'♥':'♡'}</button></article>`}
function home(){const upcoming=DATA.schedule.filter(a=>a.day===state.day).slice(0,3);return `<section class="hero"><div class="eyebrow">v3.0 · Offline PWA</div><h1>${t('welcome')}</h1><p>${t('hero')}</p><div class="hero-stats"><div class="stat"><b>${DATA.schedule.length}</b><small>${t('acts')}</small></div><div class="stat"><b>${state.plan.length}</b><small>${t('saved')}</small></div><div class="stat"><b>${Object.keys(state.journal).length}</b><small>${t('journal')}</small></div></div></section><section class="quick-grid"><button class="quick" data-route="schedule"><span>▶</span><strong>${t('now')}</strong><small>${t('nowSub')}</small></button><button class="quick" data-route="discover"><span>✦</span><strong>${t('discover')}</strong><small>${t('discoverSub')}</small></button><button class="quick" data-route="plan"><span>♥</span><strong>${t('plan')}</strong><small>${t('planSub')}</small></button><button class="quick" data-route="recommendations"><span>◎</span><strong>${t('recommend')}</strong><small>${t('recommendSub')}</small></button></section><div class="section-head"><div><h2>${t('today')}</h2><p>${t('demo')}</p></div><button class="link-button" data-route="schedule">${t('navSchedule')} →</button></div><div class="timeline">${upcoming.map(card).join('')}</div>`}
function filters(){const genres=["All",...new Set(Object.values(DATA.artists).map(a=>a.genre))];return `<div class="filter-row">${genres.map(g=>`<button data-genre="${g}" class="${state.genre===g?'active':''}">${g==='All'?t('all'):g}</button>`).join('')}</div>`}
function schedule(){let list=DATA.schedule.filter(a=>a.day===state.day&&(state.genre==='All'||artist(a.artist).genre===state.genre));return `<div class="section-head"><div><h1>${t('schedule')}</h1><p>${t('scheduleSub')}</p></div></div><div class="day-tabs">${DAY_LABELS[state.lang].map((d,i)=>`<button data-day="${i}" class="${state.day===i?'active':''}">${d}</button>`).join('')}</div>${filters()}<div class="timeline">${list.length?list.map(card).join(''):`<div class="empty">${t('noMatch')}</div>`}</div>`}
function discover(recommend=false){const savedGenres=state.plan.map(id=>artist(actById(id).artist).genre);let list=DATA.schedule.filter(a=>!state.plan.includes(a.id));if(recommend&&savedGenres.length)list.sort((a,b)=>savedGenres.includes(artist(b.artist).genre)-savedGenres.includes(artist(a.artist).genre));return `<div class="section-head"><div><h1>${recommend?t('forYou'):t('discover')}</h1><p>${recommend?t('forYouSub'):t('discoverSub')}</p></div></div>${filters()}<div class="card-grid">${list.filter(a=>state.genre==='All'||artist(a.artist).genre===state.genre).slice(0,8).map(a=>`<article class="recommendation"><span class="badge">${a.stage}</span><span class="badge">${artist(a.artist).genre}</span><h3>${a.artist}</h3><p class="meta">${DAY_LABELS[state.lang][a.day]} · ${a.start}–${a.end}</p><button class="primary" data-artist="${a.artist}">${t('openProfile')}</button></article>`).join('')}</div>`}
function plan(){const list=state.plan.map(actById).filter(Boolean).sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));return `<div class="section-head"><div><h1>${t('plan')}</h1><p>${t('planSub')}</p></div></div><div class="timeline">${list.length?list.map(card).join(''):`<div class="empty">${t('emptyPlan')}</div>`}</div>`}
function journal(){const list=state.plan.map(actById).filter(Boolean);return `<div class="section-head"><div><h1>${t('journalTitle')}</h1><p>${t('journalSub')}</p></div></div>${list.length?list.map(a=>{const j=state.journal[a.id]||{rating:0,note:""};return `<article class="journal-card"><h3>${a.artist} <span class="meta">· ${DAY_LABELS[state.lang][a.day]} ${a.start}</span></h3><div class="stars">${[1,2,3,4,5].map(n=>`<button data-rate="${a.id}:${n}" class="${j.rating>=n?'on':''}">★</button>`).join('')}</div><textarea data-note="${a.id}" placeholder="${t('notes')}">${j.note||''}</textarea></article>`}).join(''):`<div class="empty">${t('emptyJournal')}</div>`}`}
function render(){updateChrome();$("#app").innerHTML=state.route==='home'?home():state.route==='schedule'?schedule():state.route==='discover'?discover():state.route==='recommendations'?discover(true):state.route==='plan'?plan():journal();bind()}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save,i=state.plan.indexOf(id);i<0?state.plan.push(id):state.plan.splice(i,1);toast(t(i<0?'savedToast':'removedToast'));persist();render()});document.querySelectorAll('[data-artist]').forEach(b=>b.onclick=()=>showArtist(b.dataset.artist));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=+b.dataset.day;render()});document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{state.genre=b.dataset.genre;render()});document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{const[id,r]=b.dataset.rate.split(':');state.journal[id]={...(state.journal[id]||{}),rating:+r};persist();render()});document.querySelectorAll('[data-note]').forEach(el=>el.onchange=()=>{state.journal[el.dataset.note]={...(state.journal[el.dataset.note]||{}),note:el.value};persist()})}
function showArtist(name){const a=artist(name),country=new Intl.DisplayNames([state.lang],{type:'region'}).of(a.country);$("#artistContent").innerHTML=`<div class="eyebrow">${a.genre}</div><h2>${name}</h2><p><b>${t('country')}:</b> ${country}</p><div class="profile-links">${Object.entries(a.links).map(([k,v])=>`<a href="${v}" target="_blank" rel="noopener">${k} ↗</a>`).join('')}</div>`;$("#artistDialog").showModal()}
function toast(x){const el=$("#toast");el.textContent=x;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
async function enableNotifications(){if(!('Notification'in window)){toast(t('remindersOff'));return}const p=await Notification.requestPermission();toast(p==='granted'?t('remindersOn'):t('remindersOff'));localStorage.ozNotify=p==='granted'?'1':'0'}
function reminderCheck(){if(localStorage.ozNotify!=='1'||Notification.permission!=='granted')return;const now=new Date(),key=now.toISOString().slice(0,10);state.plan.map(actById).forEach(a=>{const [h,m]=a.start.split(':').map(Number),start=new Date();start.setHours(h,m,0,0);const diff=start-now;if(diff>0&&diff<=15*60000&&!localStorage[`ozReminded-${key}-${a.id}`]){new Notification(`${a.artist} · ${a.stage}`,{body:`${a.start} · ${Math.ceil(diff/60000)} min`,icon:'icons/icon-192.png'});localStorage[`ozReminded-${key}-${a.id}`]='1'}})}
$("#language").onchange=e=>{state.lang=e.target.value;localStorage.ozLang=state.lang;render()};$("#notificationButton").onclick=enableNotifications;$(".dialog-close").onclick=()=>$("#artistDialog").close();window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));setInterval(reminderCheck,60000);render();
