const RAW=window.OZORA_SCHEDULE||[];
const DATES=window.OZORA_DATES||[];
const VISIUM=RAW.filter(a=>a.stage==='Visium Garden');
const SCHEDULE=RAW.filter(a=>a.stage!=='Visium Garden').map(a=>{
  if(a.stage!=='Dragon Nest / Cooking Groove')return a;
  const hour=Number(a.start.split(':')[0]);
  return {...a,stage:hour>=10&&hour<17?'Cooking Groove':"Dragon's Nest"};
});
const LIVE_SCHEDULE=SCHEDULE.filter(a=>a.day>=2&&a.day<=8);
const STAGES=['Ozora Stage','The Dome','Cooking Groove',"Dragon's Nest",'Pumpui'];
const COLORS={'Ozora Stage':'#ff4f62','The Dome':'#f2a33a','Cooking Groove':'#df8b32',"Dragon's Nest":'#36c96d','Pumpui':'#d100d7'};
const POSTERS=[['Ozora Stage','stage-ozora.jpg'],['Pumpui','stage-pumpui.jpg'],['The Dome','stage-dome.jpg'],["Dragon's Nest / Cooking Groove",'stage-dragon-cooking.jpg'],['Visium Garden / Ambyss','stage-visium.jpg']];
const IS_ACTS=new Set(['Astrix','Merkaba','Asgard','Kalya Scintilla','Avalon']);
const FIRST={
  dont:['Astrix','Shpongle','Avalon','Hilight Tribe'],
  core:['Ace Ventura','Merkaba','Asgard','Kalya Scintilla'],
  reset:['Solar Fields','Zen Baboon','Nick Interchill','Globular']
};
const KOFI_URL='https://ko-fi.com/';

const I18N={
de:{home:'Start',all:'Alle',live:'Live',myPlan:'Mein Plan',journal:'Notizen',routing:'Routing',first:'First Timer',search:'Acts durchsuchen …',allDays:'Alle Tage',allActs:'Alle Acts',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Festival-Ablauf',arrival:'Anreise',arrivalSub:'Fr 24.7.',preDays:'Pumpui Pre-Days',preDaysSub:'Sa 25.7. + So 26.7.',openStages:'Alle Stages öffnen',openStagesSub:'Mo 27.7.',closing:'Festivalende',closingSub:'Di 4.8.',acts:'Acts',stages:'Stages',saved:'gespeichert',ratings:'Ratings',schedule:'Zeitplan',filters:'Filter',duration:'Dauer',minutes:'Min.',personalRange:'Persönlicher Bereich',commentPlaceholder:'Your personal comment (English)',share:'Plan teilen',clearAll:'Alle löschen',emptyPlan:'Noch keine Acts gespeichert.',emptyRating:'Bewerte Acts ab 7, um dein Routing zu erzeugen.',liveNow:'Jetzt live',nextActs:'Als Nächstes',nothingLive:'Aktuell läuft auf diesen fünf Stages nichts.',conflicts:'Wichtige Überschneidungen',alternative:'Alternative',recommendation:'Empfehlung',firstIntro:'Orientierung für den ersten Ozora-Besuch.',missingAmbyss:'Die gelieferten Ambyss/Visium-Daten beginnen erst am 28.7. Für Ambyss/Y2KZERO am 25.–26.7. fehlen noch die Poster oder die Act-Liste.',credit:'First-Timer-Konzept und Community-Credit: Astro S / PsySmurfs.',dontMiss:"DON'T MISS",core:'CORE',reset:'RESET',posters:'Originalposter',clearCache:'Cache wurde geleert.',copied:'Plan wurde kopiert.',removed:'Aus dem Plan entfernt.',added:'Zum Plan hinzugefügt.',confirmClear:'Wirklich den gesamten Plan löschen?',chooseLanguage:'Wähle deine Sprache',continue:'Weiter',disclaimer:'Inoffizielle Fan-App. Nicht mit O.Z.O.R.A. Festival verbunden. Zeitplan vor Ort prüfen.',helpTitle:'Anleitung',close:'Schließen',intro:'Überblick',install:'Installation',navigation:'Navigation',planHelp:'Mein Plan',ratingHelp:'Ratings',liveHelp:'Live-Anzeige',routingHelp:'Routing',offline:'Offline',privacy:'Datenschutz',helpTexts:['Die App bündelt fünf Hauptstages und die Pumpui Pre-Days.','In Safari/Chrome über „Zum Home-Bildschirm“ installieren.','Tabs, Tagesfilter, Suche und Ratingfilter kombinieren.','Stern antippen, teilen oder vollständig leeren.','Min/Max von 0–10 setzen; 9+ wird hervorgehoben.','Live- und Next-Badges aktualisieren sich jede Minute.','Acts ab 7 werden gruppiert; Überschneidungen erscheinen als Alternativen.','Poster, Plan, Ratings und UI funktionieren nach dem ersten Laden offline.','Kein Login, keine Tracker; Daten bleiben lokal im Browser.']},
en:{home:'Home',all:'All',live:'Live',myPlan:'My Plan',journal:'Notes',routing:'Routing',first:'First Timer',search:'Search all acts …',allDays:'All days',allActs:'All acts',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Festival timeline',arrival:'Arrival day',arrivalSub:'Fri 24 Jul',preDays:'Pumpui Pre-Days',preDaysSub:'Sat 25 + Sun 26 Jul',openStages:'All stages open',openStagesSub:'Mon 27 Jul',closing:'Festival ends',closingSub:'Tue 4 Aug',acts:'Acts',stages:'Stages',saved:'saved',ratings:'Ratings',schedule:'Schedule',filters:'Filters',duration:'Duration',minutes:'min',personalRange:'Personal range',commentPlaceholder:'Your personal comment (English)',share:'Share plan',clearAll:'Clear all',emptyPlan:'No acts saved yet.',emptyRating:'Rate acts 7 or higher to build your routing.',liveNow:'Live now',nextActs:'Up next',nothingLive:'Nothing is currently playing on these five stages.',conflicts:'Key overlaps',alternative:'Alternative',recommendation:'Recommendation',firstIntro:'Orientation for your first Ozora visit.',missingAmbyss:'The supplied Ambyss/Visium data starts on 28 Jul. The Ambyss/Y2KZERO poster or act list for 25–26 Jul is still missing.',credit:'First-timer concept and community credit: Astro S / PsySmurfs.',dontMiss:"DON'T MISS",core:'CORE',reset:'RESET',posters:'Original posters',clearCache:'Cache cleared.',copied:'Plan copied.',removed:'Removed from plan.',added:'Added to plan.',confirmClear:'Clear the entire plan?',chooseLanguage:'Choose your language',continue:'Continue',disclaimer:'Unofficial fan app. Not affiliated with O.Z.O.R.A. Festival. Verify times on site.',helpTitle:'Guide',close:'Close',intro:'Overview',install:'Installation',navigation:'Navigation',planHelp:'My Plan',ratingHelp:'Ratings',liveHelp:'Live display',routingHelp:'Routing',offline:'Offline',privacy:'Privacy',helpTexts:['The app combines five main stages and the Pumpui Pre-Days.','Install from Safari/Chrome using “Add to Home Screen”.','Combine tabs, day filters, search and rating filters.','Tap the star, share the plan or clear it completely.','Set a 0–10 min/max range; 9+ is highlighted.','Live and next badges update every minute.','Acts rated 7+ are grouped; overlaps appear as alternatives.','Posters, plan, ratings and UI work offline after the first load.','No login or trackers; data stays in your browser.']},
es:{home:'Inicio',all:'Todos',live:'En vivo',myPlan:'Mi plan',journal:'Notas',routing:'Rutas',first:'Primera vez',search:'Buscar actuaciones …',allDays:'Todos los días',allActs:'Todas',rating7:'7+',rating8:'8+',rating9:'9+ ÉPICO',festival:'Cronología del festival',arrival:'Llegada',arrivalSub:'Vie 24/7',preDays:'Pre-Days de Pumpui',preDaysSub:'Sáb 25 + Dom 26/7',openStages:'Abren todos los escenarios',openStagesSub:'Lun 27/7',closing:'Fin del festival',closingSub:'Mar 4/8',acts:'Actuaciones',stages:'Escenarios',saved:'guardadas',ratings:'Valoraciones',schedule:'Horario',filters:'Filtros',duration:'Duración',minutes:'min',personalRange:'Rango personal',commentPlaceholder:'Your personal comment (English)',share:'Compartir plan',clearAll:'Borrar todo',emptyPlan:'Aún no hay actuaciones guardadas.',emptyRating:'Valora actuaciones con 7 o más para crear tu ruta.',liveNow:'Ahora en vivo',nextActs:'A continuación',nothingLive:'Ahora mismo no hay actuaciones en estos cinco escenarios.',conflicts:'Cruces importantes',alternative:'Alternativa',recommendation:'Recomendación',firstIntro:'Orientación para tu primera visita a Ozora.',missingAmbyss:'Los datos de Ambyss/Visium proporcionados empiezan el 28/7. Falta el póster o la lista de Ambyss/Y2KZERO del 25–26/7.',credit:'Concepto First Timer y crédito de comunidad: Astro S / PsySmurfs.',dontMiss:'IMPERDIBLE',core:'ESENCIAL',reset:'DESCANSO',posters:'Pósteres originales',clearCache:'Caché borrada.',copied:'Plan copiado.',removed:'Eliminado del plan.',added:'Añadido al plan.',confirmClear:'¿Borrar todo el plan?',chooseLanguage:'Elige tu idioma',continue:'Continuar',disclaimer:'Aplicación no oficial. Sin afiliación con O.Z.O.R.A. Festival. Comprueba los horarios allí.',helpTitle:'Guía',close:'Cerrar',intro:'Resumen',install:'Instalación',navigation:'Navegación',planHelp:'Mi plan',ratingHelp:'Valoraciones',liveHelp:'En vivo',routingHelp:'Rutas',offline:'Sin conexión',privacy:'Privacidad',helpTexts:['La app reúne cinco escenarios principales y los Pre-Days de Pumpui.','Instálala desde Safari/Chrome con “Añadir a pantalla de inicio”.','Combina pestañas, días, búsqueda y filtros de valoración.','Pulsa la estrella, comparte o borra el plan.','Define un rango mínimo/máximo de 0–10; 9+ se resalta.','Los indicadores Live y Next se actualizan cada minuto.','Las actuaciones con 7+ se agrupan; los cruces aparecen como alternativas.','Pósteres, plan, valoraciones e interfaz funcionan offline tras la primera carga.','Sin cuenta ni rastreadores; los datos quedan en el navegador.']},
hu:{home:'Kezdőlap',all:'Mind',live:'Élő',myPlan:'Tervem',journal:'Jegyzetek',routing:'Útvonal',first:'Első alkalom',search:'Fellépők keresése …',allDays:'Minden nap',allActs:'Minden fellépő',rating7:'7+',rating8:'8+',rating9:'9+ EPIC',festival:'Fesztivál-idővonal',arrival:'Érkezés',arrivalSub:'Júl. 24., péntek',preDays:'Pumpui előnapok',preDaysSub:'Júl. 25–26.',openStages:'Minden színpad nyit',openStagesSub:'Júl. 27., hétfő',closing:'Fesztivál vége',closingSub:'Aug. 4., kedd',acts:'Fellépések',stages:'Színpadok',saved:'mentve',ratings:'Értékelések',schedule:'Program',filters:'Szűrők',duration:'Időtartam',minutes:'perc',personalRange:'Személyes tartomány',commentPlaceholder:'Your personal comment (English)',share:'Terv megosztása',clearAll:'Összes törlése',emptyPlan:'Még nincs mentett fellépő.',emptyRating:'Értékeld 7 fölé a fellépőket az útvonalhoz.',liveNow:'Most élőben',nextActs:'Következik',nothingLive:'Jelenleg egyik színpadon sincs műsor.',conflicts:'Fontos átfedések',alternative:'Alternatíva',recommendation:'Ajánlás',firstIntro:'Segítség az első Ozora-látogatáshoz.',missingAmbyss:'A kapott Ambyss/Visium adatok július 28-án kezdődnek. A július 25–26-i Ambyss/Y2KZERO plakát vagy fellépőlista még hiányzik.',credit:'First Timer koncepció és közösségi kredit: Astro S / PsySmurfs.',dontMiss:'KI NE HAGYD',core:'ALAP',reset:'PIHENŐ',posters:'Eredeti plakátok',clearCache:'Gyorsítótár törölve.',copied:'Terv másolva.',removed:'Eltávolítva a tervből.',added:'Hozzáadva a tervhez.',confirmClear:'Törlöd a teljes tervet?',chooseLanguage:'Válassz nyelvet',continue:'Tovább',disclaimer:'Nem hivatalos rajongói app. Nem áll kapcsolatban az O.Z.O.R.A. Fesztivállal. A helyszínen ellenőrizd az időpontokat.',helpTitle:'Útmutató',close:'Bezárás',intro:'Áttekintés',install:'Telepítés',navigation:'Navigáció',planHelp:'Tervem',ratingHelp:'Értékelések',liveHelp:'Élő kijelzés',routingHelp:'Útvonal',offline:'Offline',privacy:'Adatvédelem',helpTexts:['Az app öt fő színpadot és a Pumpui előnapokat fogja össze.','Safari/Chrome: „Hozzáadás a Főképernyőhöz”.','Kombináld a füleket, napokat, keresést és értékelésszűrőt.','Csillaggal ments, oszd meg vagy töröld a tervet.','Állíts be 0–10 minimum/maximum tartományt; a 9+ kiemelt.','A Live és Next jelvény percenként frissül.','A 7+ fellépők csoportosítva jelennek meg, az átfedések alternatívák.','A plakátok, terv, értékelések és felület az első betöltés után offline működik.','Nincs bejelentkezés vagy követés; az adatok a böngészőben maradnak.']}
};
const UI_LABELS={
  de:{language:'Sprache',compact:'Kompaktmodus',guide:'Anleitung',cache:'Cache leeren',areas:'Bereiche',mainNav:'Hauptnavigation',close:'Schließen',artist:'Künstlerprofil',comment:'Kommentar und Rating',opening:'Eröffnungszeremonie'},
  en:{language:'Language',compact:'Compact mode',guide:'Guide',cache:'Clear cache',areas:'Sections',mainNav:'Main navigation',close:'Close',artist:'Artist profile',comment:'Comment and rating',opening:'Opening Ceremony'},
  es:{language:'Idioma',compact:'Modo compacto',guide:'Guía',cache:'Borrar caché',areas:'Secciones',mainNav:'Navegación principal',close:'Cerrar',artist:'Perfil del artista',comment:'Comentario y valoración',opening:'Ceremonia de apertura'},
  hu:{language:'Nyelv',compact:'Kompakt mód',guide:'Útmutató',cache:'Gyorsítótár törlése',areas:'Területek',mainNav:'Fő navigáció',close:'Bezárás',artist:'Előadói profil',comment:'Megjegyzés és értékelés',opening:'Megnyitó ünnepség'}
};

const safeJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}};
let state={route:location.hash.slice(1)||'home',lang:localStorage.ozLang||'de',day:'all',stage:'all',rating:0,search:'',plan:safeJSON('ozPlanV4',[]),reviews:safeJSON('ozReviewsV4',{}),compact:localStorage.ozCompact==='1'};
const $=s=>document.querySelector(s),t=k=>I18N[state.lang][k]??k;
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dateLabel=i=>new Intl.DateTimeFormat(state.lang,{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(`${DATES[i]}T12:00:00`));
const mins=x=>{const[h,m]=x.split(':').map(Number);return h*60+m};
const duration=a=>{let d=mins(a.end)-mins(a.start);if(d<=0)d+=1440;return d};
const startDate=a=>new Date(`${DATES[a.day]}T${a.start}:00`);
const endDate=a=>{const e=new Date(`${DATES[a.day]}T${a.end}:00`);if(e<=startDate(a))e.setDate(e.getDate()+1);return e};
const review=id=>state.reviews[id]||{min:0,max:0,comment:''};
const score=id=>{const r=review(id);return (Number(r.min)+Number(r.max))/2};
const links=name=>({YouTube:`https://www.youtube.com/results?search_query=${encodeURIComponent(name+' live')}`,Spotify:`https://open.spotify.com/search/${encodeURIComponent(name)}`});
const persist=()=>{localStorage.ozPlanV4=JSON.stringify(state.plan);localStorage.ozReviewsV4=JSON.stringify(state.reviews);localStorage.ozLang=state.lang;localStorage.ozCompact=state.compact?'1':'0'};

function statusFor(a,now=new Date()){
  if(now>=startDate(a)&&now<endDate(a))return 'live';
  const next=SCHEDULE.filter(x=>x.stage===a.stage&&startDate(x)>now).sort((x,y)=>startDate(x)-startDate(y))[0];
  return next?.id===a.id?'next':'';
}
function stageColor(stage){return COLORS[stage]||'#888'}
function ratingText(id){const r=state.reviews[id];return r?`${Number(r.min).toFixed(1)}–${Number(r.max).toFixed(1)}`:'–'}
function card(a,open=false){const r=review(a.id),status=statusFor(a),epic=score(a.id)>=9,saved=state.plan.includes(a.id),l=links(a.artist),ui=UI_LABELS[state.lang],artist=esc(a.artist);return `<article class="act-card ${epic?'epic':''} ${open?'open':''}" style="--stage:${stageColor(a.stage)}" data-card="${esc(a.id)}"><div class="act-main"><div class="time">${a.start}<small>${a.end} · ${duration(a)} ${t('minutes')}</small></div><div><button class="artist-button" data-artist="${artist}" aria-label="${ui.artist}: ${artist}">${artist}</button><div><span class="stage-badge">${esc(a.stage)}</span>${IS_ACTS.has(a.artist)?'<span class="tag is">🪶 IS</span>':''}${status?`<span class="status-badge ${status}">${status==='live'?'● LIVE':'NEXT'}</span>`:''}<span class="rating-badge">${ratingText(a.id)}</span></div><div class="meta">${esc(a.genre)} · ${esc(a.type)}</div></div><div class="row-actions"><a href="${l.YouTube}" target="_blank" rel="noopener" aria-label="YouTube">▶</a><a href="${l.Spotify}" target="_blank" rel="noopener" aria-label="Spotify">♫</a><button data-detail="${esc(a.id)}" aria-label="${ui.comment}">💬</button><button data-save="${esc(a.id)}" class="${saved?'saved':''}" aria-label="${t('myPlan')}">${saved?'★':'☆'}</button></div></div><div class="details"><div class="rating-sliders"><label>${t('personalRange')} min: <b data-min-label="${esc(a.id)}">${Number(r.min).toFixed(1)}</b><input data-min="${esc(a.id)}" type="range" min="0" max="10" step="0.5" value="${r.min}"></label><label>${t('personalRange')} max: <b data-max-label="${esc(a.id)}">${Number(r.max).toFixed(1)}</b><input data-max="${esc(a.id)}" type="range" min="0" max="10" step="0.5" value="${r.max}"></label></div><textarea data-comment="${esc(a.id)}" placeholder="${t('commentPlaceholder')}">${esc(r.comment||'')}</textarea></div></article>`}

function featureTabs(){const items=[['all',`${t('all')} (${SCHEDULE.length})`],...STAGES.map(s=>[s,`${s} (${SCHEDULE.filter(a=>a.stage===s).length})`]),['routing',t('routing')],['first',t('first')]];$('#featureTabs').innerHTML=items.map(([id,label])=>`<button data-feature="${id}" class="${(id==='all'&&state.route==='schedule'&&state.stage==='all')||(STAGES.includes(id)&&state.route==='schedule'&&state.stage===id)||state.route===id?'active':''}">${label}</button>`).join('')}
function chrome(){const ui=UI_LABELS[state.lang];document.documentElement.lang=state.lang;document.body.classList.toggle('compact',state.compact);document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));$('#language').value=state.lang;$('#language').ariaLabel=ui.language;$('#compactButton').title=$('#compactButton').ariaLabel=ui.compact;$('#infoButton').title=$('#infoButton').ariaLabel=ui.guide;$('#cacheButton').title=$('#cacheButton').ariaLabel=ui.cache;$('#featureTabs').ariaLabel=ui.areas;$('.bottom-nav').ariaLabel=ui.mainNav;document.querySelectorAll('.dialog-close').forEach(b=>b.ariaLabel=ui.close);$('#planCount').textContent=state.plan.length;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));featureTabs()}
function go(route){state.route=route;location.hash=route;render()}
function home(){return `<section class="hero"><div class="eyebrow">v4.1 · Offline PWA · Unofficial</div><h1>YOUR FESTIVAL.<br>YOUR FLOW.</h1><p>${t('disclaimer')}</p><div class="stats"><div class="stat"><b>${SCHEDULE.length}</b><small>${t('acts')}</small></div><div class="stat"><b>5</b><small>${t('stages')}</small></div><div class="stat"><b>${state.plan.length}</b><small>${t('saved')}</small></div><div class="stat"><b>${Object.keys(state.reviews).length}</b><small>${t('ratings')}</small></div></div></section><section class="quick-grid"><button class="quick hot" data-route="live"><span>●</span><strong>${t('liveNow')}</strong><small>${t('nextActs')}</small></button><button class="quick" data-route="schedule"><span>▦</span><strong>${t('schedule')}</strong><small>${SCHEDULE.length} ${t('acts')}</small></button><button class="quick" data-route="plan"><span>☆</span><strong>${t('myPlan')}</strong><small>${state.plan.length} ${t('saved')}</small></button><button class="quick" data-route="routing"><span>↳</span><strong>${t('routing')}</strong><small>7+ · ${t('conflicts')}</small></button><button class="quick" data-route="first"><span>◎</span><strong>${t('first')}</strong><small>DON'T MISS · CORE · RESET</small></button><button class="quick" data-route="journal"><span>✎</span><strong>${t('journal')}</strong><small>${t('ratings')}</small></button></section><div class="section-head"><h2>${t('festival')}</h2></div><section class="festival-box"><div class="festival-step"><b>${t('arrival')}</b><small>${t('arrivalSub')}</small></div><div class="festival-step"><b>${t('preDays')}</b><small>${t('preDaysSub')}</small></div><div class="festival-step"><b>${t('openStages')}</b><small>${t('openStagesSub')}</small></div><div class="festival-step"><b>${t('closing')}</b><small>${t('closingSub')}</small></div></section><div class="section-head"><h2>${UI_LABELS[state.lang].opening}</h2></div><div class="timeline">${SCHEDULE.filter(a=>a.artist==='Opening Ceremony').map(card).join('')}</div>`}
function filters(){return `<div class="controls"><input id="search" class="search" type="search" value="${state.search}" placeholder="${t('search')}"><div class="filter-row">${['all',...DATES.map((_,i)=>String(i))].map(v=>`<button data-day="${v}" class="${String(state.day)===v?'active':''}">${v==='all'?t('allDays'):dateLabel(Number(v))}</button>`).join('')}</div><div class="filter-row">${[[0,t('allActs')],[7,t('rating7')],[8,t('rating8')],[9,t('rating9')]].map(([v,l])=>`<button data-rating="${v}" class="${state.rating===v?'active':''}">${l}</button>`).join('')}</div></div>`}
function filtered(){const q=state.search.trim().toLocaleLowerCase();return SCHEDULE.filter(a=>(state.day==='all'||a.day===Number(state.day))&&(state.stage==='all'||a.stage===state.stage)&&score(a.id)>=state.rating&&(!q||`${a.artist} ${a.stage} ${a.genre}`.toLocaleLowerCase().includes(q)))}
function grouped(list){const days=[...new Set(list.map(a=>a.day))];return days.map(d=>`<section class="day-group"><h2>${dateLabel(d)}</h2><div class="timeline">${list.filter(a=>a.day===d).map(a=>card(a)).join('')}</div></section>`).join('')}
function posters(){return `<div class="poster-row">${POSTERS.map(([n,f])=>`<a href="${f}?v=410" target="_blank" rel="noopener"><img src="${f}?v=410" alt="${n}"><b>${n}</b></a>`).join('')}</div>`}
function schedule(){const list=filtered();return `<div class="section-head"><div><h1>${state.stage==='all'?t('schedule'):state.stage}</h1><p>${list.length} ${t('acts')}</p></div></div>${filters()}${list.length?grouped(list):`<div class="empty">${t('allActs')}: 0</div>`}<div class="section-head"><h2>${t('posters')}</h2></div>${posters()}`}
function plan(){const list=state.plan.map(id=>SCHEDULE.find(a=>a.id===id)).filter(Boolean).sort((a,b)=>a.day-b.day||mins(a.start)-mins(b.start));return `<div class="section-head"><div><h1>☆ ${t('myPlan')}</h1><p>${list.length} ${t('saved')}</p></div><div class="plan-actions"><button class="secondary" id="sharePlan">${t('share')}</button><button class="danger" id="clearPlan">${t('clearAll')}</button></div></div>${list.length?grouped(list):`<div class="empty">${t('emptyPlan')}</div>`}`}
function journal(){const list=SCHEDULE.filter(a=>state.reviews[a.id]||state.plan.includes(a.id));return `<div class="section-head"><div><h1>✎ ${t('journal')}</h1><p>${list.length} ${t('acts')}</p></div></div>${list.length?grouped(list.map(a=>a)):`<div class="empty">${t('emptyPlan')}</div>`}`}
function live(){const now=new Date(),live=LIVE_SCHEDULE.filter(a=>now>=startDate(a)&&now<endDate(a));const next=STAGES.map(stage=>LIVE_SCHEDULE.filter(a=>a.stage===stage&&startDate(a)>now).sort((a,b)=>startDate(a)-startDate(b))[0]).filter(Boolean);return `<div class="section-head"><div><h1>● ${t('liveNow')}</h1><p id="liveClock">${new Intl.DateTimeFormat(state.lang,{dateStyle:'medium',timeStyle:'short'}).format(now)}</p></div></div>${live.length?`<div class="timeline">${live.map(card).join('')}</div>`:`<div class="empty">${t('nothingLive')}</div>`}<div class="section-head"><h2>${t('nextActs')}</h2></div>${next.length?`<div class="timeline">${next.map(card).join('')}</div>`:`<div class="empty">${t('nothingLive')}</div>`}`}
function overlaps(list){const pairs=[];for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(a.day===b.day&&a.stage!==b.stage&&startDate(a)<endDate(b)&&startDate(b)<endDate(a))pairs.push([a,b])}return pairs.sort((x,y)=>Math.max(score(y[0].id),score(y[1].id))-Math.max(score(x[0].id),score(x[1].id)))}
function routing(){
  const list=SCHEDULE.filter(a=>score(a.id)>=7);
  const pairs=overlaps(list);
  const days=[...new Set(list.map(a=>a.day))];
  const conflictMarkup=pairs.length
    ? `<div class="section-head"><h2>${t('conflicts')}</h2></div>${pairs.slice(0,5).map(([a,b])=>`<div class="conflict"><strong>${dateLabel(a.day)} · ${a.start}</strong><div>${a.artist} (${ratingText(a.id)})</div><div>↳ ${t('alternative')}: ${b.artist} (${ratingText(b.id)})</div><small>${t('recommendation')}: ${score(a.id)>=score(b.id)?a.artist:b.artist}</small></div>`).join('')}`
    : '';
  const dayMarkup=days.length
    ? days.map(d=>`<section class="route-day"><h2>${dateLabel(d)}</h2>${list.filter(a=>a.day===d).map(a=>card(a)).join('')}</section>`).join('')
    : `<div class="empty">${t('emptyRating')}</div>`;
  return `<div class="section-head"><div><h1>↳ ${t('routing')}</h1><p>7+ · ${list.length} ${t('acts')}</p></div></div>${conflictMarkup}${dayMarkup}`;
}
function pickGroup(kind,names){const items=names.map(n=>SCHEDULE.find(a=>a.artist===n)).filter(Boolean);return `<article class="first-card"><h3 class="${kind}">${t(kind==='dont'?'dontMiss':kind)}</h3>${items.map(a=>`<div><b>${a.artist}</b><div class="meta">${dateLabel(a.day)} · ${a.start} · ${a.stage}${IS_ACTS.has(a.artist)?' · 🪶 IS':''}</div></div>`).join('')}</article>`}
function first(){return `<div class="section-head"><div><h1>${t('first')}</h1><p>${t('firstIntro')}</p></div><button class="primary" data-route="schedule">${t('all')} ${SCHEDULE.length} ${t('acts')}</button></div><div class="first-grid">${pickGroup('dont',FIRST.dont)}${pickGroup('core',FIRST.core)}${pickGroup('reset',FIRST.reset)}</div><p class="notice">${t('credit')}</p><div class="section-head"><h2>Ambyss / Y2KZERO</h2></div><p class="notice">${t('missingAmbyss')}</p><div class="section-head"><h2>${t('posters')}</h2></div>${posters()}`}
function render(){chrome();$('#app').innerHTML=state.route==='home'?home():state.route==='schedule'?schedule():state.route==='plan'?plan():state.route==='journal'?journal():state.route==='live'?live():state.route==='routing'?routing():first();bind()}

function bind(){
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));
  document.querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>{const v=b.dataset.feature;if(v==='all'){state.stage='all';state.day='all';state.rating=0;state.search='';go('schedule')}else if(STAGES.includes(v)){state.stage=v;go('schedule')}else go(v)});
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{state.day=b.dataset.day;render()});
  document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{state.rating=Number(b.dataset.rating);render()});
  const search=$('#search');if(search)search.oninput=e=>{const value=e.target.value;state.search=value;render();const next=$('#search');next.focus();next.setSelectionRange(value.length,value.length)};
  document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save,i=state.plan.indexOf(id);i<0?state.plan.push(id):state.plan.splice(i,1);persist();toast(t(i<0?'added':'removed'));render()});
  document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>document.querySelector(`[data-card="${b.dataset.detail}"]`)?.classList.toggle('open'));
  document.querySelectorAll('[data-min]').forEach(el=>el.oninput=e=>saveRange(e.target.dataset.min,'min',Number(e.target.value)));
  document.querySelectorAll('[data-max]').forEach(el=>el.oninput=e=>saveRange(e.target.dataset.max,'max',Number(e.target.value)));
  document.querySelectorAll('[data-comment]').forEach(el=>el.onchange=e=>{const id=e.target.dataset.comment;state.reviews[id]={...review(id),comment:e.target.value};persist()});
  document.querySelectorAll('[data-artist]').forEach(b=>b.onclick=()=>showArtist(b.dataset.artist));
  const share=$('#sharePlan');if(share)share.onclick=sharePlan;const clear=$('#clearPlan');if(clear)clear.onclick=()=>{if(confirm(t('confirmClear'))){state.plan=[];persist();render()}};
}
function saveRange(id,key,value){const r={...review(id),[key]:value};if(r.min>r.max){if(key==='min')r.max=r.min;else r.min=r.max}state.reviews[id]=r;persist();document.querySelector(`[data-min-label="${id}"]`).textContent=Number(r.min).toFixed(1);document.querySelector(`[data-max-label="${id}"]`).textContent=Number(r.max).toFixed(1);document.querySelector(`[data-min="${id}"]`).value=r.min;document.querySelector(`[data-max="${id}"]`).value=r.max}
function showArtist(name){const occurrences=SCHEDULE.filter(a=>a.artist===name),l=links(name);$('#artistContent').innerHTML=`<div class="eyebrow">${UI_LABELS[state.lang].artist}</div><h2>${esc(name)}</h2>${IS_ACTS.has(name)?'<p><span class="tag is">🪶 Indian Spirit</span></p>':''}<div class="profile-links"><a href="${l.YouTube}" target="_blank" rel="noopener">▶ YouTube</a><a href="${l.Spotify}" target="_blank" rel="noopener">♫ Spotify</a></div><h3>${t('schedule')}</h3>${occurrences.map(a=>`<p>${dateLabel(a.day)} · ${a.start}–${a.end} · ${esc(a.stage)}</p>`).join('')}`;$('#artistDialog').showModal()}
async function sharePlan(){const text=state.plan.map(id=>SCHEDULE.find(a=>a.id===id)).filter(Boolean).sort((a,b)=>a.day-b.day||mins(a.start)-mins(b.start)).map(a=>`${dateLabel(a.day)} ${a.start} ${a.artist} — ${a.stage}`).join('\n');try{if(navigator.share)await navigator.share({title:'My Ozora 2026 Plan',text});else{await navigator.clipboard.writeText(text);toast(t('copied'))}}catch(error){if(error.name!=='AbortError')console.error(error)}}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function instructions(){const tr=I18N[state.lang],heads=['intro','install','navigation','planHelp','ratingHelp','liveHelp','routingHelp','offline','privacy'];$('#infoContent').innerHTML=`<h2>${t('helpTitle')}</h2>${heads.map((h,i)=>`<section class="help-section"><h3>${i+1}. ${t(h)}</h3><p>${tr.helpTexts[i]}</p></section>`).join('')}`}
async function clearCache(){if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(r=>r.unregister()))}if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}toast(t('clearCache'));setTimeout(()=>location.reload(),700)}

$('#language').onchange=e=>{state.lang=e.target.value;persist();render()};
$('#compactButton').onclick=()=>{state.compact=!state.compact;persist();render()};
$('#infoButton').onclick=()=>{instructions();$('#infoDialog').showModal()};
$('#cacheButton').onclick=clearCache;
$('#qrButton').onclick=()=>$('#qrDialog').showModal();
$('#kofiLink').href=KOFI_URL;
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('selected',x===b));persist();chrome()});
$('#introContinue').onclick=()=>{localStorage.ozIntroSeen='1';$('#introDialog').close();render();instructions();$('#infoDialog').showModal()};
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const reg=await navigator.serviceWorker.register('./service-worker.js?v=410',{updateViaCache:'none'});reg.update();if(localStorage.ozIntroSeen!=='1')$('#introDialog').showModal()});
setInterval(()=>{if(state.route==='live'||state.route==='schedule')render()},60000);
render();
