(()=>{
const headerKey=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const artistKey=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'');
const numberRange=value=>{if(value==null||value==='')return null;const values=String(value).replace(/,/g,'.').match(/\d+(?:\.\d+)?/g)?.map(Number).filter(number=>number>=0&&number<=10)||[];if(!values.length)return null;const first=values[0],second=values[1]??first;return {min:Math.min(first,second),max:Math.max(first,second)}};
const truthy=value=>value===true||value===1||['true','yes','ja','x','1'].includes(String(value??'').trim().toLowerCase());
const timeValue=value=>{if(typeof value==='number'){const total=Math.round((value-Math.floor(value))*1440)%1440;return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}const match=String(value??'').match(/(\d{1,2}):(\d{2})/);return match?`${match[1].padStart(2,'0')}:${match[2]}`:''};
const urls=value=>{const found=String(value??'').match(/https?:\/\/[^\s;]+/g)||[];return {youtube:found.find(url=>/youtu(?:be\.com|\.be)/i.test(url))||'',spotify:found.find(url=>/spotify\.com/i.test(url))||''}};
const stageValue=value=>{const key=artistKey(value);if(key.includes('ozora')||key.includes('mainstage'))return 'Ozora Stage';if(key.includes('dome'))return 'The Dome';if(key.includes('pumpui'))return 'Pumpui';if(key.includes('cooking'))return 'Cooking Groove';if(key.includes('dragon'))return "Dragon's Nest";return String(value??'').trim()};
const cellText=(cell,shared)=>{const type=cell.getAttribute('t'),value=cell.getElementsByTagName('v')[0]?.textContent??'';if(type==='s')return shared[Number(value)]??'';if(type==='inlineStr')return [...cell.getElementsByTagName('t')].map(node=>node.textContent??'').join('');if(type==='b')return value==='1';if(type==='str')return value;if(value==='')return '';const number=Number(value);return Number.isFinite(number)?number:value};
const columnIndex=reference=>{const letters=(reference.match(/[A-Z]+/i)||['A'])[0].toUpperCase();let index=0;for(const letter of letters)index=index*26+letter.charCodeAt(0)-64;return index-1};
async function worksheetRows(zip,path,shared){const file=zip.file(path);if(!file)return [];const document=new DOMParser().parseFromString(await file.async('text'),'application/xml');return [...document.getElementsByTagName('row')].map(row=>{const values=[];for(const cell of row.getElementsByTagName('c'))values[columnIndex(cell.getAttribute('r')||'A')]=cellText(cell,shared);return values})}
async function workbookSheets(file){if(!window.JSZip)throw new Error('JSZip missing');const zip=await JSZip.loadAsync(await file.arrayBuffer());const parser=new DOMParser();const sharedFile=zip.file('xl/sharedStrings.xml');const shared=sharedFile?[...parser.parseFromString(await sharedFile.async('text'),'application/xml').getElementsByTagName('si')].map(item=>[...item.getElementsByTagName('t')].map(node=>node.textContent??'').join('')):[];const workbook=parser.parseFromString(await zip.file('xl/workbook.xml').async('text'),'application/xml');const relationships=parser.parseFromString(await zip.file('xl/_rels/workbook.xml.rels').async('text'),'application/xml');const targets=new Map([...relationships.getElementsByTagName('Relationship')].map(item=>[item.getAttribute('Id'),item.getAttribute('Target')]));const sheets=[];for(const sheet of workbook.getElementsByTagName('sheet')){const name=sheet.getAttribute('name')||'Sheet';const id=sheet.getAttribute('r:id');const target=targets.get(id)||'';const path=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^xl\//,'')}`;sheets.push({name,rows:await worksheetRows(zip,path,shared)})}return sheets}
function matchesFor(row,schedule){if(row.id){const exact=schedule.find(act=>act.id===String(row.id).trim());if(exact)return [exact]}const key=artistKey(row.artist);if(!key)return [];let matches=schedule.filter(act=>artistKey(act.artist)===key);const stage=stageValue(row.stage);if(stage&&matches.some(act=>act.stage===stage))matches=matches.filter(act=>act.stage===stage);const start=timeValue(row.start);if(start&&matches.some(act=>act.start===start))matches=matches.filter(act=>act.start===start);return matches}
function recordFromValues(values,schedule,priority=2){const range=values.range||numberRange(values.rating);const links=urls(values.link);const matches=matchesFor(values,schedule);return {matches,record:{ids:matches.map(act=>act.id),artist:String(values.artist??'').trim(),min:range?.min,max:range?.max,comment:String(values.comment??'').trim(),youtube:String(values.youtube||links.youtube||'').trim(),spotify:String(values.spotify||links.spotify||'').trim(),plan:truthy(values.plan),indianSpirit:truthy(values.indianSpirit),priority}}}
function standardRecords(sheet,schedule){const headers=sheet.rows[0]?.map(headerKey)||[],column=name=>headers.indexOf(name),records=[],unmatched=[],numeric=value=>value==null||String(value).trim()===''?NaN:Number(value);for(const row of sheet.rows.slice(1)){const values={id:row[column('id')],artist:row[column('artist')],stage:row[column('stage')],start:row[column('start')],range:{min:numeric(row[column('ratingmin')]),max:numeric(row[column('ratingmax')])},comment:row[column('commentenglish')],youtube:row[column('youtubeurl')],spotify:row[column('spotifyurl')],indianSpirit:row[column('indianspirit2026')],plan:row[column('addtomyplan')]};if(!values.artist)continue;if(!Number.isFinite(values.range.min)&&!Number.isFinite(values.range.max))values.range=null;else{if(!Number.isFinite(values.range.min))values.range.min=values.range.max;if(!Number.isFinite(values.range.max))values.range.max=values.range.min}const parsed=recordFromValues(values,schedule,3);if(parsed.matches.length)records.push(parsed.record);else unmatched.push(String(values.artist))}return {records,unmatched}}
function johannesSpec(name){const key=headerKey(name);if(key.includes('coooking')||key.includes('cooking'))return {startRow:2,start:0,artist:1,stage:2,rating:3,comment:4,link:5,priority:3};if(key.includes('mainstage'))return {startRow:2,start:1,artist:2,stageValue:'Ozora Stage',rating:3,comment:5,link:6,priority:3};if(key.includes('dome'))return {startRow:2,start:1,artist:2,stageValue:'The Dome',rating:3,comment:6,link:7,priority:3};if(key==='tabelle3'||key.includes('pumpui'))return {startRow:3,start:1,artist:2,stageValue:'Pumpui',rating:3,comment:6,link:7,priority:3};if(key.includes('burningmountain'))return {startRow:16,artist:0,rating:1,comment:4,link:5,priority:1};return null}
function johannesRecords(sheets,schedule){const records=[],unmatched=[];for(const sheet of sheets){const spec=johannesSpec(sheet.name);if(!spec)continue;for(const row of sheet.rows.slice(spec.startRow)){const artist=row[spec.artist];if(typeof artist!=='string'||!artist.trim())continue;const parsed=recordFromValues({artist,start:spec.start==null?'':row[spec.start],stage:spec.stageValue||row[spec.stage],rating:row[spec.rating],comment:row[spec.comment],link:row[spec.link]},schedule,spec.priority);if(parsed.matches.length)records.push(parsed.record);else if(row[spec.rating]!=null||row[spec.comment]!=null)unmatched.push(artist.trim())}}return {records,unmatched}}
function mergeRecords(records){const byId=new Map();for(const record of records){for(const id of record.ids){const current=byId.get(id)||{id,artist:record.artist,min:null,max:null,comment:'',youtube:'',spotify:'',plan:false,indianSpirit:false,priority:0};const stronger=record.priority>=current.priority;if(record.min!=null&&stronger){current.min=record.min;current.max=record.max}if(record.comment&&stronger)current.comment=record.comment;if(record.youtube&&stronger)current.youtube=record.youtube;if(record.spotify&&stronger)current.spotify=record.spotify;current.plan=current.plan||record.plan;current.indianSpirit=current.indianSpirit||record.indianSpirit;current.priority=Math.max(current.priority,record.priority);byId.set(id,current)}}return [...byId.values()]}
async function parseFile(file,schedule){const sheets=await workbookSheets(file);const standard=sheets.find(sheet=>sheet.name.toLowerCase()==='import'&&sheet.rows[0]?.map(headerKey).includes('id'));const parsed=standard?standardRecords(standard,schedule):johannesRecords(sheets,schedule);return {kind:standard?'template':'johannes',fileName:file.name,sheets:sheets.map(sheet=>sheet.name),records:mergeRecords(parsed.records),unmatched:[...new Set(parsed.unmatched)].slice(0,30)}}
window.OZORA_XLSX_IMPORT={parseFile,artistKey,numberRange};
})();
